[package]
publish = false
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
heck = "0.5.0"
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
roxmltree = "0.21.1"
serde = { version = "1.0.229", features = ["derive"] }
syn = { version = "3.0.6", features = ["full"] }
toml = "1.1.7"

[dev-dependencies]
insta = "1.49.0"
