[package]
name = "authorizenet-derive"
description = "Derive macros for the authorizenet crate (XML mapping)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/authorizenet-derive"
keywords = ["authorize-net", "xml", "derive"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.6", features = ["full", "extra-traits"] }

[lib]
proc-macro = true
