// @generated by `cargo xtask codegen` from schema/AnetApiSchema.xsd and
// schema/overrides.toml. Do not edit by hand.

use crate::xml::AnetEnum;

/// XSD: `authIndicatorEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum AuthIndicator {
    #[anet(value = "pre")]
    Pre,
    #[anet(value = "final")]
    Final,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `bankAccountTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum BankAccountType {
    #[anet(value = "checking")]
    Checking,
    #[anet(value = "savings")]
    Savings,
    #[anet(value = "businessChecking")]
    BusinessChecking,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `echeckTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum EcheckType {
    #[anet(value = "PPD")]
    Ppd,
    #[anet(value = "WEB")]
    Web,
    #[anet(value = "CCD")]
    Ccd,
    #[anet(value = "TEL")]
    Tel,
    #[anet(value = "ARC")]
    Arc,
    #[anet(value = "BOC")]
    Boc,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `paymentMethodEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum PaymentMethod {
    #[anet(value = "creditCard")]
    CreditCard,
    #[anet(value = "eCheck")]
    ECheck,
    #[anet(value = "payPal")]
    PayPal,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `cardTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum CardType {
    #[anet(value = "Visa")]
    Visa,
    #[anet(value = "MasterCard")]
    MasterCard,
    #[anet(value = "AmericanExpress")]
    AmericanExpress,
    #[anet(value = "Discover")]
    Discover,
    #[anet(value = "JCB")]
    Jcb,
    #[anet(value = "DinersClub")]
    DinersClub,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `accountTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum AccountType {
    #[anet(value = "Visa")]
    Visa,
    #[anet(value = "MasterCard")]
    MasterCard,
    #[anet(value = "AmericanExpress")]
    AmericanExpress,
    #[anet(value = "Discover")]
    Discover,
    #[anet(value = "JCB")]
    Jcb,
    #[anet(value = "DinersClub")]
    DinersClub,
    #[anet(value = "eCheck")]
    ECheck,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `customerTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum CustomerType {
    #[anet(value = "individual")]
    Individual,
    #[anet(value = "business")]
    Business,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `ARBSubscriptionUnitEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum ArbSubscriptionUnit {
    #[anet(value = "days")]
    Days,
    #[anet(value = "months")]
    Months,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `validationModeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum ValidationMode {
    #[anet(value = "none")]
    None,
    #[anet(value = "testMode")]
    TestMode,
    #[anet(value = "liveMode")]
    LiveMode,
    #[anet(value = "oldLiveMode")]
    OldLiveMode,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `splitTenderStatusEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum SplitTenderStatus {
    #[anet(value = "completed")]
    Completed,
    #[anet(value = "held")]
    Held,
    #[anet(value = "voided")]
    Voided,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `ARBSubscriptionStatusEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum ArbSubscriptionStatus {
    #[anet(value = "active")]
    Active,
    #[anet(value = "expired")]
    Expired,
    #[anet(value = "suspended")]
    Suspended,
    #[anet(value = "canceled")]
    Canceled,
    #[anet(value = "terminated")]
    Terminated,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `transactionTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum TransactionType {
    #[anet(value = "authOnlyTransaction")]
    AuthOnlyTransaction,
    #[anet(value = "authCaptureTransaction")]
    AuthCaptureTransaction,
    #[anet(value = "captureOnlyTransaction")]
    CaptureOnlyTransaction,
    #[anet(value = "refundTransaction")]
    RefundTransaction,
    #[anet(value = "priorAuthCaptureTransaction")]
    PriorAuthCaptureTransaction,
    #[anet(value = "voidTransaction")]
    VoidTransaction,
    #[anet(value = "getDetailsTransaction")]
    GetDetailsTransaction,
    #[anet(value = "authOnlyContinueTransaction")]
    AuthOnlyContinueTransaction,
    #[anet(value = "authCaptureContinueTransaction")]
    AuthCaptureContinueTransaction,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `transactionStatusEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum TransactionStatus {
    #[anet(value = "authorizedPendingCapture")]
    AuthorizedPendingCapture,
    #[anet(value = "capturedPendingSettlement")]
    CapturedPendingSettlement,
    #[anet(value = "communicationError")]
    CommunicationError,
    #[anet(value = "refundSettledSuccessfully")]
    RefundSettledSuccessfully,
    #[anet(value = "refundPendingSettlement")]
    RefundPendingSettlement,
    #[anet(value = "approvedReview")]
    ApprovedReview,
    #[anet(value = "declined")]
    Declined,
    #[anet(value = "couldNotVoid")]
    CouldNotVoid,
    #[anet(value = "expired")]
    Expired,
    #[anet(value = "generalError")]
    GeneralError,
    #[anet(value = "pendingFinalSettlement")]
    PendingFinalSettlement,
    #[anet(value = "pendingSettlement")]
    PendingSettlement,
    #[anet(value = "failedReview")]
    FailedReview,
    #[anet(value = "settledSuccessfully")]
    SettledSuccessfully,
    #[anet(value = "settlementError")]
    SettlementError,
    #[anet(value = "underReview")]
    UnderReview,
    #[anet(value = "updatingSettlement")]
    UpdatingSettlement,
    #[anet(value = "voided")]
    Voided,
    #[anet(value = "FDSPendingReview")]
    FdsPendingReview,
    #[anet(value = "FDSAuthorizedPendingReview")]
    FdsAuthorizedPendingReview,
    #[anet(value = "returnedItem")]
    ReturnedItem,
    #[anet(value = "chargeback")]
    Chargeback,
    #[anet(value = "chargebackReversal")]
    ChargebackReversal,
    #[anet(value = "authorizedPendingRelease")]
    AuthorizedPendingRelease,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `settlementStateEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum SettlementState {
    #[anet(value = "settledSuccessfully")]
    SettledSuccessfully,
    #[anet(value = "settlementError")]
    SettlementError,
    #[anet(value = "pendingSettlement")]
    PendingSettlement,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `FDSFilterActionEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum FdsFilterAction {
    #[anet(value = "reject")]
    Reject,
    #[anet(value = "decline")]
    Decline,
    #[anet(value = "hold")]
    Hold,
    #[anet(value = "authAndHold")]
    AuthAndHold,
    #[anet(value = "report")]
    Report,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `permissionsEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum Permissions {
    #[anet(value = "API_Merchant_BasicReporting")]
    ApiMerchantBasicReporting,
    #[anet(value = "Submit_Charge")]
    SubmitCharge,
    #[anet(value = "Submit_Refund")]
    SubmitRefund,
    #[anet(value = "Submit_Update")]
    SubmitUpdate,
    #[anet(value = "Mobile_Admin")]
    MobileAdmin,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `deviceActivationEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum DeviceActivation {
    #[anet(value = "Activate")]
    Activate,
    #[anet(value = "Disable")]
    Disable,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `TransactionGroupStatusEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum TransactionGroupStatus {
    #[anet(value = "any")]
    Any,
    #[anet(value = "pendingApproval")]
    PendingApproval,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `afdsTransactionEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum AfdsTransaction {
    #[anet(value = "approve")]
    Approve,
    #[anet(value = "decline")]
    Decline,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `customerProfileTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum CustomerProfileType {
    #[anet(value = "regular")]
    Regular,
    #[anet(value = "guest")]
    Guest,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `webCheckOutTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum WebCheckOutType {
    #[anet(value = "PAN")]
    Pan,
    #[anet(value = "TOKEN")]
    Token,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `OperationType`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum Operation {
    #[anet(value = "DECRYPT")]
    Decrypt,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `EncryptionAlgorithmType`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum EncryptionAlgorithm {
    #[anet(value = "TDES")]
    Tdes,
    #[anet(value = "AES")]
    Aes,
    #[anet(value = "RSA")]
    Rsa,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `EncodingType`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum Encoding {
    #[anet(value = "Base64")]
    Base64,
    #[anet(value = "Hex")]
    Hex,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `settingNameEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum SettingName {
    #[anet(value = "emailCustomer")]
    EmailCustomer,
    #[anet(value = "merchantEmail")]
    MerchantEmail,
    #[anet(value = "allowPartialAuth")]
    AllowPartialAuth,
    #[anet(value = "headerEmailReceipt")]
    HeaderEmailReceipt,
    #[anet(value = "footerEmailReceipt")]
    FooterEmailReceipt,
    #[anet(value = "recurringBilling")]
    RecurringBilling,
    #[anet(value = "duplicateWindow")]
    DuplicateWindow,
    #[anet(value = "testRequest")]
    TestRequest,
    #[anet(value = "hostedProfileReturnUrl")]
    HostedProfileReturnUrl,
    #[anet(value = "hostedProfileReturnUrlText")]
    HostedProfileReturnUrlText,
    #[anet(value = "hostedProfilePageBorderVisible")]
    HostedProfilePageBorderVisible,
    #[anet(value = "hostedProfileIFrameCommunicatorUrl")]
    HostedProfileIFrameCommunicatorUrl,
    #[anet(value = "hostedProfileHeadingBgColor")]
    HostedProfileHeadingBgColor,
    #[anet(value = "hostedProfileValidationMode")]
    HostedProfileValidationMode,
    #[anet(value = "hostedProfileBillingAddressRequired")]
    HostedProfileBillingAddressRequired,
    #[anet(value = "hostedProfileCardCodeRequired")]
    HostedProfileCardCodeRequired,
    #[anet(value = "hostedProfileBillingAddressOptions")]
    HostedProfileBillingAddressOptions,
    #[anet(value = "hostedProfileManageOptions")]
    HostedProfileManageOptions,
    #[anet(value = "hostedPaymentIFrameCommunicatorUrl")]
    HostedPaymentIFrameCommunicatorUrl,
    #[anet(value = "hostedPaymentButtonOptions")]
    HostedPaymentButtonOptions,
    #[anet(value = "hostedPaymentReturnOptions")]
    HostedPaymentReturnOptions,
    #[anet(value = "hostedPaymentOrderOptions")]
    HostedPaymentOrderOptions,
    #[anet(value = "hostedPaymentPaymentOptions")]
    HostedPaymentPaymentOptions,
    #[anet(value = "hostedPaymentBillingAddressOptions")]
    HostedPaymentBillingAddressOptions,
    #[anet(value = "hostedPaymentShippingAddressOptions")]
    HostedPaymentShippingAddressOptions,
    #[anet(value = "hostedPaymentSecurityOptions")]
    HostedPaymentSecurityOptions,
    #[anet(value = "hostedPaymentCustomerOptions")]
    HostedPaymentCustomerOptions,
    #[anet(value = "hostedPaymentStyleOptions")]
    HostedPaymentStyleOptions,
    #[anet(value = "typeEmailReceipt")]
    TypeEmailReceipt,
    #[anet(value = "hostedProfilePaymentOptions")]
    HostedProfilePaymentOptions,
    #[anet(value = "hostedProfileSaveButtonText")]
    HostedProfileSaveButtonText,
    #[anet(value = "hostedPaymentVisaCheckoutOptions")]
    HostedPaymentVisaCheckoutOptions,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `DeliveryMethodEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum DeliveryMethod {
    #[anet(value = "EMAIL")]
    Email,
    #[anet(value = "SMS")]
    Sms,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `messageTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum MessageType {
    #[anet(value = "Ok")]
    Ok,
    #[anet(value = "Error")]
    Error,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `TransactionListOrderFieldEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum TransactionListOrderField {
    #[anet(value = "id")]
    Id,
    #[anet(value = "submitTimeUTC")]
    SubmitTimeUtc,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `ARBGetSubscriptionListSearchTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum ArbGetSubscriptionListSearchType {
    #[anet(value = "cardExpiringThisMonth")]
    CardExpiringThisMonth,
    #[anet(value = "subscriptionActive")]
    SubscriptionActive,
    #[anet(value = "subscriptionExpiringThisMonth")]
    SubscriptionExpiringThisMonth,
    #[anet(value = "subscriptionInactive")]
    SubscriptionInactive,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `ARBGetSubscriptionListOrderFieldEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum ArbGetSubscriptionListOrderField {
    #[anet(value = "id")]
    Id,
    #[anet(value = "name")]
    Name,
    #[anet(value = "status")]
    Status,
    #[anet(value = "createTimeStampUTC")]
    CreateTimeStampUtc,
    #[anet(value = "lastName")]
    LastName,
    #[anet(value = "firstName")]
    FirstName,
    #[anet(value = "accountNumber")]
    AccountNumber,
    #[anet(value = "amount")]
    Amount,
    #[anet(value = "pastOccurrences")]
    PastOccurrences,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `CustomerPaymentProfileOrderFieldEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum CustomerPaymentProfileOrderField {
    #[anet(value = "id")]
    Id,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `CustomerPaymentProfileSearchTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum CustomerPaymentProfileSearchType {
    #[anet(value = "cardsExpiringInMonth")]
    CardsExpiringInMonth,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `AUJobTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum AuJobType {
    #[anet(value = "all")]
    All,
    #[anet(value = "updates")]
    Updates,
    #[anet(value = "deletes")]
    Deletes,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `merchantInitTransReasonEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum MerchantInitTransReason {
    #[anet(value = "resubmission")]
    Resubmission,
    #[anet(value = "delayedCharge")]
    DelayedCharge,
    #[anet(value = "reauthorization")]
    Reauthorization,
    #[anet(value = "noShow")]
    NoShow,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}

/// XSD: `paymentMethodsTypeEnum`
#[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
#[non_exhaustive]
pub enum PaymentMethodsType {
    #[anet(value = "Visa")]
    Visa,
    #[anet(value = "MasterCard")]
    MasterCard,
    #[anet(value = "Discover")]
    Discover,
    #[anet(value = "AmericanExpress")]
    AmericanExpress,
    #[anet(value = "DinersClub")]
    DinersClub,
    #[anet(value = "JCB")]
    Jcb,
    #[anet(value = "EnRoute")]
    EnRoute,
    #[anet(value = "Echeck")]
    Echeck,
    #[anet(value = "Paypal")]
    Paypal,
    #[anet(value = "VisaCheckout")]
    VisaCheckout,
    #[anet(value = "ApplePay")]
    ApplePay,
    #[anet(value = "AndroidPay")]
    AndroidPay,
    #[anet(value = "GooglePay")]
    GooglePay,
    /// A value the schema does not list.
    #[anet(other)]
    Other(String),
}
