// @generated by `cargo xtask codegen` from schema/AnetApiSchema.xsd and
// schema/overrides.toml. Do not edit by hand.

use bon::Builder;
use crate::types::XmlDateTime;
use crate::xml::AnetXml;
#[allow(unused_imports)]
use super::*;

/// XSD: `<decryptPaymentDataRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "decryptPaymentDataRequest", request)]
#[non_exhaustive]
pub struct DecryptPaymentDataRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub opaque_data: OpaqueData,
    pub call_id: Option<String>,
}

/// XSD: `<decryptPaymentDataResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "decryptPaymentDataResponse")]
#[non_exhaustive]
pub struct DecryptPaymentDataResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub shipping_info: Option<CustomerAddress>,
    pub billing_info: Option<CustomerAddress>,
    pub card_info: Option<CreditCardMasked>,
    pub payment_details: Option<PaymentDetails>,
}

/// ===========Encryption Start ==========================
///
/// XSD: `<securePaymentContainerRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "securePaymentContainerRequest", request)]
#[non_exhaustive]
pub struct SecurePaymentContainerRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub data: WebCheckOutData,
}

/// XSD: `<securePaymentContainerResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "securePaymentContainerResponse")]
#[non_exhaustive]
pub struct SecurePaymentContainerResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub opaque_data: OpaqueData,
}

/// errorResponse
/// This is the response when an error occurs before the method can
/// be determined, such as an "unknown method" type of error.
///
/// XSD: `<ErrorResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ErrorResponse")]
#[non_exhaustive]
pub struct ErrorResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to test the availability of the API.
///
/// XSD: `<isAliveRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "isAliveRequest")]
#[non_exhaustive]
pub struct IsAliveRequest {
    pub ref_id: Option<String>,
}

/// This is the response to isAliveRequest.
///
/// XSD: `<isAliveResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "isAliveResponse")]
#[non_exhaustive]
pub struct IsAliveResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to test the availability of the API.
///
/// XSD: `<authenticateTestRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "authenticateTestRequest", request)]
#[non_exhaustive]
pub struct AuthenticateTestRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
}

/// This is the response to authenticateTestRequest.
///
/// XSD: `<authenticateTestResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "authenticateTestResponse")]
#[non_exhaustive]
pub struct AuthenticateTestResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to create a new ARB subscription.
/// The merchant must be signed up for the ARB service to use it.
///
/// XSD: `<ARBCreateSubscriptionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBCreateSubscriptionRequest", request)]
#[non_exhaustive]
pub struct ArbCreateSubscriptionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub subscription: ArbSubscription,
}

/// This is the response to ARBCreateSubscriptionRequest.
///
/// XSD: `<ARBCreateSubscriptionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBCreateSubscriptionResponse")]
#[non_exhaustive]
pub struct ArbCreateSubscriptionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub subscription_id: Option<String>,
    pub profile: Option<CustomerProfileId>,
}

/// This method is used to update an existing ARB subscription.
/// The merchant must be signed up for the ARB service to use it.
///
/// XSD: `<ARBUpdateSubscriptionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBUpdateSubscriptionRequest", request)]
#[non_exhaustive]
pub struct ArbUpdateSubscriptionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub subscription_id: String,
    pub subscription: ArbSubscription,
}

/// This is the response to ARBUpdateSubscriptionResponse.
///
/// XSD: `<ARBUpdateSubscriptionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBUpdateSubscriptionResponse")]
#[non_exhaustive]
pub struct ArbUpdateSubscriptionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub profile: Option<CustomerProfileId>,
}

/// This method is used to cancel an existing ARB subscription.
/// The merchant must be signed up for the ARB service to use it.
///
/// XSD: `<ARBCancelSubscriptionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBCancelSubscriptionRequest", request)]
#[non_exhaustive]
pub struct ArbCancelSubscriptionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub subscription_id: String,
}

/// This is the response to ARBCancelSubscriptionRequest.
///
/// XSD: `<ARBCancelSubscriptionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBCancelSubscriptionResponse")]
#[non_exhaustive]
pub struct ArbCancelSubscriptionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to get the status of an existing ARB subscription.
/// The merchant must be signed up for the ARB service to use it.
///
/// XSD: `<ARBGetSubscriptionStatusRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBGetSubscriptionStatusRequest", request)]
#[non_exhaustive]
pub struct ArbGetSubscriptionStatusRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub subscription_id: String,
}

/// This is the response to ARBGetSubscriptionStatusRequest.
///
/// XSD: `<ARBGetSubscriptionStatusResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBGetSubscriptionStatusResponse")]
#[non_exhaustive]
pub struct ArbGetSubscriptionStatusResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub status: Option<ArbSubscriptionStatus>,
}

/// This method is used to create a new customer profile along with any
/// customer payment profiles and customer shipping addresses for the customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<createCustomerProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerProfileRequest", request)]
#[non_exhaustive]
pub struct CreateCustomerProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub profile: CustomerProfile,
    pub validation_mode: Option<ValidationMode>,
}

/// This is the response to createCustomerProfileRequest.
///
/// XSD: `<createCustomerProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerProfileResponse")]
#[non_exhaustive]
pub struct CreateCustomerProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub customer_profile_id: Option<String>,
    #[anet(wrapper, item = "numericString", keep_empty)]
    #[builder(default)]
    pub customer_payment_profile_id_list: Vec<String>,
    #[anet(wrapper, item = "numericString", keep_empty)]
    #[builder(default)]
    pub customer_shipping_address_id_list: Vec<String>,
    #[anet(wrapper, item = "string", keep_empty)]
    #[builder(default)]
    pub validation_direct_response_list: Vec<String>,
}

/// This method is used to create a new customer payment profile for an existing customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<createCustomerPaymentProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerPaymentProfileRequest", request)]
#[non_exhaustive]
pub struct CreateCustomerPaymentProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub payment_profile: CustomerPaymentProfile,
    pub validation_mode: Option<ValidationMode>,
}

/// This is the response to createCustomerPaymentProfileRequest.
///
/// XSD: `<createCustomerPaymentProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerPaymentProfileResponse")]
#[non_exhaustive]
pub struct CreateCustomerPaymentProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub customer_profile_id: Option<String>,
    pub customer_payment_profile_id: Option<String>,
    pub validation_direct_response: Option<String>,
}

/// This method is used to create a new customer shipping address for an existing customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<createCustomerShippingAddressRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerShippingAddressRequest", request)]
#[non_exhaustive]
pub struct CreateCustomerShippingAddressRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub address: CustomerAddress,
    pub default_shipping_address: Option<bool>,
}

/// This is the response to createCustomerShippingAddressRequest.
///
/// XSD: `<createCustomerShippingAddressResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerShippingAddressResponse")]
#[non_exhaustive]
pub struct CreateCustomerShippingAddressResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub customer_profile_id: Option<String>,
    pub customer_address_id: Option<String>,
}

/// This method is used to create a Customer profile, payment profile, and shipping profile
/// from an existing successful transaction.
///
/// XSD: `<createCustomerProfileFromTransactionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerProfileFromTransactionRequest", request)]
#[non_exhaustive]
pub struct CreateCustomerProfileFromTransactionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub trans_id: String,
    pub customer: Option<CustomerProfileBase>,
    pub customer_profile_id: Option<String>,
    pub default_payment_profile: Option<bool>,
    pub default_shipping_address: Option<bool>,
    pub profile_type: Option<CustomerProfileType>,
}

/// This method is used to retrieve an existing customer profile along with all the
/// customer payment profiles and customer shipping addresses for the customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<getCustomerProfileRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerProfileRequest", request)]
#[non_exhaustive]
pub struct GetCustomerProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: Option<String>,
    pub merchant_customer_id: Option<String>,
    pub email: Option<String>,
    pub unmask_expiration_date: Option<bool>,
    pub include_issuer_info: Option<bool>,
}

/// This is the response to getCustomerProfileRequest.
///
/// XSD: `<getCustomerProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerProfileResponse")]
#[non_exhaustive]
pub struct GetCustomerProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub profile: Option<CustomerProfileMasked>,
    #[anet(wrapper, item = "subscriptionId")]
    #[builder(default)]
    pub subscription_ids: Vec<String>,
}

/// This method is used to retrieve an existing customer payment profile for a customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<getCustomerPaymentProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerPaymentProfileRequest", request)]
#[non_exhaustive]
pub struct GetCustomerPaymentProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub customer_payment_profile_id: Option<String>,
    pub unmask_expiration_date: Option<bool>,
    pub include_issuer_info: Option<bool>,
}

/// This is the response to getCustomerPaymentProfileRequest.
///
/// XSD: `<getCustomerPaymentProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerPaymentProfileResponse")]
#[non_exhaustive]
pub struct GetCustomerPaymentProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub payment_profile: Option<CustomerPaymentProfileMasked>,
}

/// This method is used to retrieve an existing customer shipping address for a customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<getCustomerShippingAddressRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerShippingAddressRequest", request)]
#[non_exhaustive]
pub struct GetCustomerShippingAddressRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub customer_address_id: Option<String>,
}

/// This is the response to getCustomerShippingAddressRequest.
///
/// XSD: `<getCustomerShippingAddressResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerShippingAddressResponse")]
#[non_exhaustive]
pub struct GetCustomerShippingAddressResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub default_shipping_address: Option<bool>,
    pub address: Option<CustomerAddressEx>,
    #[anet(wrapper, item = "subscriptionId")]
    #[builder(default)]
    pub subscription_ids: Vec<String>,
}

/// This method is used to update an existing customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<updateCustomerProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateCustomerProfileRequest", request)]
#[non_exhaustive]
pub struct UpdateCustomerProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub profile: CustomerProfileInfoEx,
}

/// This is the response to updateCustomerProfileRequest.
///
/// XSD: `<updateCustomerProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateCustomerProfileResponse")]
#[non_exhaustive]
pub struct UpdateCustomerProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to update an existing customer payment profile for a customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<updateCustomerPaymentProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateCustomerPaymentProfileRequest", request)]
#[non_exhaustive]
pub struct UpdateCustomerPaymentProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub payment_profile: CustomerPaymentProfileEx,
    pub validation_mode: Option<ValidationMode>,
}

/// This is the response to updateCustomerPaymentProfileRequest.
///
/// XSD: `<updateCustomerPaymentProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateCustomerPaymentProfileResponse")]
#[non_exhaustive]
pub struct UpdateCustomerPaymentProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub validation_direct_response: Option<String>,
}

/// This method is used to update an existing customer shipping address for a customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<updateCustomerShippingAddressRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateCustomerShippingAddressRequest", request)]
#[non_exhaustive]
pub struct UpdateCustomerShippingAddressRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub address: CustomerAddressEx,
    pub default_shipping_address: Option<bool>,
}

/// This is the response to updateCustomerShippingAddressRequest.
///
/// XSD: `<updateCustomerShippingAddressResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateCustomerShippingAddressResponse")]
#[non_exhaustive]
pub struct UpdateCustomerShippingAddressResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to delete an existing customer profile along with all the
/// customer payment profiles and customer shipping addresses for the customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<deleteCustomerProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "deleteCustomerProfileRequest", request)]
#[non_exhaustive]
pub struct DeleteCustomerProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
}

/// This is the response to deleteCustomerProfileRequest.
///
/// XSD: `<deleteCustomerProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "deleteCustomerProfileResponse")]
#[non_exhaustive]
pub struct DeleteCustomerProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to delete an existing customer payment profile from a customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<deleteCustomerPaymentProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "deleteCustomerPaymentProfileRequest", request)]
#[non_exhaustive]
pub struct DeleteCustomerPaymentProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub customer_payment_profile_id: String,
}

/// This is the response to deleteCustomerPaymentProfileRequest.
///
/// XSD: `<deleteCustomerPaymentProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "deleteCustomerPaymentProfileResponse")]
#[non_exhaustive]
pub struct DeleteCustomerPaymentProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to delete an existing customer shipping address from a customer profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<deleteCustomerShippingAddressRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "deleteCustomerShippingAddressRequest", request)]
#[non_exhaustive]
pub struct DeleteCustomerShippingAddressRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub customer_address_id: String,
}

/// This is the response to deleteCustomerShippingAddressRequest.
///
/// XSD: `<deleteCustomerShippingAddressResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "deleteCustomerShippingAddressResponse")]
#[non_exhaustive]
pub struct DeleteCustomerShippingAddressResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to generate a payment transaction for a customer payment profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<createCustomerProfileTransactionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerProfileTransactionRequest", request)]
#[non_exhaustive]
pub struct CreateCustomerProfileTransactionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub transaction: ProfileTransaction,
    pub extra_options: Option<String>,
}

/// This is the response to createCustomerProfileTransactionRequest.
///
/// XSD: `<createCustomerProfileTransactionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createCustomerProfileTransactionResponse")]
#[non_exhaustive]
pub struct CreateCustomerProfileTransactionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub transaction_response: Option<TransactionResponse>,
    pub direct_response: Option<String>,
}

/// This method is used to check a customer payment profile by generating a test transaction for it.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<validateCustomerPaymentProfileRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "validateCustomerPaymentProfileRequest", request)]
#[non_exhaustive]
pub struct ValidateCustomerPaymentProfileRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub customer_payment_profile_id: String,
    pub customer_shipping_address_id: Option<String>,
    #[anet(sensitive)]
    pub card_code: Option<String>,
    pub validation_mode: ValidationMode,
}

/// This is the response to validateCustomerPaymentProfileRequest.
///
/// XSD: `<validateCustomerPaymentProfileResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "validateCustomerPaymentProfileResponse")]
#[non_exhaustive]
pub struct ValidateCustomerPaymentProfileResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub direct_response: Option<String>,
}

/// This method is used retrieve the customer profile ids for your account in case they get lost.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<getCustomerProfileIdsRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerProfileIdsRequest", request)]
#[non_exhaustive]
pub struct GetCustomerProfileIdsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
}

/// This is the response to getCustomerProfileIdsRequest.
///
/// XSD: `<getCustomerProfileIdsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerProfileIdsResponse")]
#[non_exhaustive]
pub struct GetCustomerProfileIdsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    #[anet(wrapper, item = "numericString", keep_empty)]
    #[builder(default)]
    pub ids: Vec<String>,
}

/// This method is used to void or release an order after getting a partial authorization for a transaction.
///
/// XSD: `<updateSplitTenderGroupRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateSplitTenderGroupRequest", request)]
#[non_exhaustive]
pub struct UpdateSplitTenderGroupRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub split_tender_id: String,
    pub split_tender_status: SplitTenderStatus,
}

/// This is the response to updateSplitTenderGroupRequest.
///
/// XSD: `<updateSplitTenderGroupResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateSplitTenderGroupResponse")]
#[non_exhaustive]
pub struct UpdateSplitTenderGroupResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to retrieve detailed information about a single transaction.
///
/// XSD: `<getTransactionDetailsRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionDetailsRequest", request)]
#[non_exhaustive]
pub struct GetTransactionDetailsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    #[anet(choice)]
    pub reference: TransactionReference,
}

/// This is the response to getTransactionDetailsRequest.
///
/// XSD: `<getTransactionDetailsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionDetailsResponse")]
#[non_exhaustive]
pub struct GetTransactionDetailsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub transaction: TransactionDetails,
    pub client_id: Option<String>,
    pub transref_id: Option<String>,
}

/// This method retrieves a lightweight summary of transaction information
/// with only 15 essential fields for improved performance.
///
/// XSD: `<getTransactionSummaryRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionSummaryRequest", request)]
#[non_exhaustive]
pub struct GetTransactionSummaryRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub trans_id: String,
}

/// This is the response to getTransactionSummaryRequest containing
/// only essential transaction fields for lightweight operations.
///
/// XSD: `<getTransactionSummaryResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionSummaryResponse")]
#[non_exhaustive]
pub struct GetTransactionSummaryResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub transaction: GetTransactionSummary,
}

/// This method is used to process transactions.
///
/// XSD: `<createTransactionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createTransactionRequest", request)]
#[non_exhaustive]
pub struct CreateTransactionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    #[anet(choice)]
    pub transaction: CreateTransactionPayload,
}

/// This is the response that will be returned to a client following
/// any type of transaction request.
///
/// XSD: `<createTransactionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "createTransactionResponse")]
#[non_exhaustive]
pub struct CreateTransactionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub transaction_response: TransactionResponse,
    pub profile_response: Option<CreateProfileResponse>,
}

/// This method is used to approve or decline suspicious transactions.
///
/// XSD: `<updateHeldTransactionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateHeldTransactionRequest", request)]
#[non_exhaustive]
pub struct UpdateHeldTransactionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub held_transaction_request: HeldTransactionRequest,
}

/// This is the response that will be returned to a client following
/// updateHeldTransactionRequest.
///
/// XSD: `<updateHeldTransactionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateHeldTransactionResponse")]
#[non_exhaustive]
pub struct UpdateHeldTransactionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub transaction_response: Option<TransactionResponse>,
}

/// This method is used to get the batch details for the specified BatchId
///
/// XSD: `<getBatchStatisticsRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getBatchStatisticsRequest", request)]
#[non_exhaustive]
pub struct GetBatchStatisticsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub batch_id: String,
}

/// This is the response to getBatchStatisticsRequest.
///
/// XSD: `<getBatchStatisticsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getBatchStatisticsResponse")]
#[non_exhaustive]
pub struct GetBatchStatisticsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub batch: Option<BatchDetails>,
}

/// This method is used to retrieve a list of settled batches.
///
/// XSD: `<getSettledBatchListRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getSettledBatchListRequest", request)]
#[non_exhaustive]
pub struct GetSettledBatchListRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub include_statistics: Option<bool>,
    pub first_settlement_date: Option<XmlDateTime>,
    pub last_settlement_date: Option<XmlDateTime>,
    pub pos_redirect_to_mint: Option<bool>,
}

/// This is the response to getSettledBatchListRequest.
///
/// XSD: `<getSettledBatchListResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getSettledBatchListResponse")]
#[non_exhaustive]
pub struct GetSettledBatchListResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    #[anet(wrapper, item = "batch")]
    #[builder(default)]
    pub batch_list: Vec<BatchDetails>,
}

/// This method is used to retrieve a list of settled transactions.
///
/// XSD: `<getTransactionListRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionListRequest", request)]
#[non_exhaustive]
pub struct GetTransactionListRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub batch_id: Option<String>,
    pub sorting: Option<TransactionListSorting>,
    pub paging: Option<Paging>,
    pub pos_redirect_to_mint: Option<bool>,
}

/// This is the response to getTransactionListRequest.
///
/// XSD: `<getTransactionListResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionListResponse")]
#[non_exhaustive]
pub struct GetTransactionListResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    #[anet(wrapper, item = "transaction")]
    #[builder(default)]
    pub transactions: Vec<TransactionSummary>,
    pub total_num_in_result_set: Option<i32>,
}

/// This method is used to give access to the hosted customer profile page to one of your customers.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<getHostedProfilePageRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getHostedProfilePageRequest", request)]
#[non_exhaustive]
pub struct GetHostedProfilePageRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    /// Allowed values for settingName are: hostedProfileReturnUrl, hostedProfileReturnUrlText, hostedProfilePageBorderVisible, hostedProfileIFrameCommunicatorUrl, hostedProfileHeadingBgColor, hostedProfileBillingAddressRequired, hostedProfileCardCodeRequired, hostedProfileBillingAddressOptions, hostedProfileManageOptions, hostedProfilePaymentOptions, hostedProfileSaveButtonText.
    pub hosted_profile_settings: Option<ArrayOfSetting>,
}

/// This is the response to getHostedProfilePageRequest.
///
/// XSD: `<getHostedProfilePageResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getHostedProfilePageResponse")]
#[non_exhaustive]
pub struct GetHostedProfilePageResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub token: String,
}

/// This method is used to retrieve a list of unsettled transactions.
///
/// XSD: `<getUnsettledTransactionListRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getUnsettledTransactionListRequest", request)]
#[non_exhaustive]
pub struct GetUnsettledTransactionListRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub status: Option<TransactionGroupStatus>,
    pub sorting: Option<TransactionListSorting>,
    pub paging: Option<Paging>,
    pub pos_redirect_to_mint: Option<bool>,
}

/// This method is used to give access to the hosted payment page to one of your customers.
///
/// XSD: `<getHostedPaymentPageRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getHostedPaymentPageRequest", request)]
#[non_exhaustive]
pub struct GetHostedPaymentPageRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub transaction_request: TransactionRequest,
    /// Allowed values for settingName are: hostedPaymentIFrameCommunicatorUrl, hostedPaymentButtonOptions, hostedPaymentReturnOptions, hostedPaymentOrderOptions, hostedPaymentPaymentOptions, hostedPaymentBillingAddressOptions, hostedPaymentShippingAddressOptions, hostedPaymentSecurityOptions, hostedPaymentCustomerOptions, hostedPaymentStyleOptions
    pub hosted_payment_settings: Option<ArrayOfSetting>,
}

/// This is the response to getHostedPaymentPageRequest.
///
/// XSD: `<getHostedPaymentPageResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getHostedPaymentPageResponse")]
#[non_exhaustive]
pub struct GetHostedPaymentPageResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub token: String,
}

/// This is the response to getUnsettledTransactionListRequest.
///
/// XSD: `<getUnsettledTransactionListResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getUnsettledTransactionListResponse")]
#[non_exhaustive]
pub struct GetUnsettledTransactionListResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    #[anet(wrapper, item = "transaction")]
    #[builder(default)]
    pub transactions: Vec<TransactionSummary>,
    pub total_num_in_result_set: Option<i32>,
}

/// This method is used to request registration for a mobile device.
///
/// XSD: `<mobileDeviceRegistrationRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceRegistrationRequest", request)]
#[non_exhaustive]
pub struct MobileDeviceRegistrationRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub mobile_device: MobileDevice,
}

/// This is the response to mobileDeviceRegistrationRequest.
///
/// XSD: `<mobileDeviceRegistrationResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceRegistrationResponse")]
#[non_exhaustive]
pub struct MobileDeviceRegistrationResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to request a PIN for mobile device login.
///
/// XSD: `<mobileDeviceLoginPinRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceLoginPinRequest", request)]
#[non_exhaustive]
pub struct MobileDeviceLoginPinRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub pin_delivery_request_enc: String,
}

/// This method is used to verify a PIN for mobile device login.
///
/// XSD: `<mobileDeviceLoginVerifyPinRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceLoginVerifyPinRequest", request)]
#[non_exhaustive]
pub struct MobileDeviceLoginVerifyPinRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub pin_verify_request_enc: String,
}

/// This method is used to verify a challenge for mobile device login.
///
/// XSD: `<mobileDeviceLoginVerifyChallengeRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceLoginVerifyChallengeRequest", request)]
#[non_exhaustive]
pub struct MobileDeviceLoginVerifyChallengeRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub pin_verify_request_enc: String,
}

/// This is the response to mobileDeviceLoginPinRequest.
///
/// XSD: `<mobileDeviceLoginPinResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceLoginPinResponse")]
#[non_exhaustive]
pub struct MobileDeviceLoginPinResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This is the response to mobileDeviceLoginVerifyPinRequest.
///
/// XSD: `<mobileDeviceLoginVerifyPinResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceLoginVerifyPinResponse")]
#[non_exhaustive]
pub struct MobileDeviceLoginVerifyPinResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This is the response to mobileDeviceLoginVerifyChallengeRequest.
///
/// XSD: `<mobileDeviceLoginVerifyChallengeResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceLoginVerifyChallengeResponse")]
#[non_exhaustive]
pub struct MobileDeviceLoginVerifyChallengeResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub merchant_contact: MerchantContact,
    #[anet(wrapper, item = "permission", keep_empty)]
    #[builder(default)]
    pub user_permissions: Vec<Permission>,
    pub merchant_account: Option<TransRetailInfo>,
    pub acceptance_devices_account: Option<AcceptanceDevicesAccount>,
}

/// This method is used to authenticate a mobile device with MFA support.
///
/// XSD: `<mobileDeviceMfaLoginRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceMfaLoginRequest", request)]
#[non_exhaustive]
pub struct MobileDeviceMfaLoginRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub signature_key: Option<String>,
}

/// This is the response to mobileDeviceMfaLoginRequest.
///
/// XSD: `<mobileDeviceMfaLoginResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "mobileDeviceMfaLoginResponse")]
#[non_exhaustive]
pub struct MobileDeviceMfaLoginResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub merchant_contact: MerchantContact,
    #[anet(wrapper, item = "permission", keep_empty)]
    #[builder(default)]
    pub user_permissions: Vec<Permission>,
    pub merchant_account: Option<TransRetailInfo>,
    pub acceptance_devices_account: Option<AcceptanceDevicesAccount>,
    #[anet(sensitive)]
    pub activation_code: Option<String>,
    pub vba_decision: Option<String>,
    pub fingerprint: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
}

/// This method is used to end a session from a mobile device.
///
/// XSD: `<logoutRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "logoutRequest", request)]
#[non_exhaustive]
pub struct LogoutRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
}

/// This is the response to logoutRequest.
///
/// XSD: `<logoutResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "logoutResponse")]
#[non_exhaustive]
pub struct LogoutResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to send a transaction email receipt.
///
/// XSD: `<sendCustomerTransactionReceiptRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "sendCustomerTransactionReceiptRequest", request)]
#[non_exhaustive]
pub struct SendCustomerTransactionReceiptRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub trans_id: String,
    pub customer_email: String,
    pub email_settings: Option<EmailSettings>,
}

/// This is the response to sendCustomerTransactionReceiptRequest.
///
/// XSD: `<sendCustomerTransactionReceiptResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "sendCustomerTransactionReceiptResponse")]
#[non_exhaustive]
pub struct SendCustomerTransactionReceiptResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// XSD: `<ARBGetSubscriptionListRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBGetSubscriptionListRequest", request)]
#[non_exhaustive]
pub struct ArbGetSubscriptionListRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub search_type: ArbGetSubscriptionListSearchType,
    pub sorting: Option<ArbGetSubscriptionListSorting>,
    pub paging: Option<Paging>,
}

/// XSD: `<ARBGetSubscriptionListResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBGetSubscriptionListResponse")]
#[non_exhaustive]
pub struct ArbGetSubscriptionListResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub total_num_in_result_set: Option<i32>,
    #[anet(wrapper, item = "subscriptionDetail")]
    #[builder(default)]
    pub subscription_details: Vec<SubscriptionDetail>,
}

/// Element definition for GetCustomerPaymentProfileList
///
/// XSD: `<getCustomerPaymentProfileListRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerPaymentProfileListRequest", request)]
#[non_exhaustive]
pub struct GetCustomerPaymentProfileListRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub search_type: CustomerPaymentProfileSearchType,
    pub month: String,
    pub sorting: Option<CustomerPaymentProfileSorting>,
    pub paging: Option<Paging>,
}

/// XSD: `<getCustomerPaymentProfileListResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerPaymentProfileListResponse")]
#[non_exhaustive]
pub struct GetCustomerPaymentProfileListResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub total_num_in_result_set: i32,
    #[anet(wrapper, item = "paymentProfile")]
    #[builder(default)]
    pub payment_profiles: Vec<CustomerPaymentProfileListItem>,
}

/// This method is used to get details of an existing ARB subscription.
/// The merchant must be signed up for the ARB service to use it.
///
/// XSD: `<ARBGetSubscriptionRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBGetSubscriptionRequest", request)]
#[non_exhaustive]
pub struct ArbGetSubscriptionRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub subscription_id: String,
    pub include_transactions: Option<bool>,
}

/// Get ARBSubscription Response
///
/// XSD: `<ARBGetSubscriptionResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "ARBGetSubscriptionResponse")]
#[non_exhaustive]
pub struct ArbGetSubscriptionResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub subscription: ArbSubscriptionMasked,
}

/// Get TransactionList For Customer Request
/// This method is used to retrieve a list of transactions for a customer profile, and optionally, a customer payment profile.
/// The merchant must be signed up for the CIM service to use it.
///
/// XSD: `<getTransactionListForCustomerRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getTransactionListForCustomerRequest", request)]
#[non_exhaustive]
pub struct GetTransactionListForCustomerRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub customer_profile_id: String,
    pub customer_payment_profile_id: Option<String>,
    pub sorting: Option<TransactionListSorting>,
    pub paging: Option<Paging>,
}

/// Get AUJobSummary Request
/// This method is used to get summary of jobs done by Account Updater.
///
/// XSD: `<getAUJobSummaryRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getAUJobSummaryRequest", request)]
#[non_exhaustive]
pub struct GetAuJobSummaryRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub month: String,
}

/// Get AUJobSummary Response
///
/// XSD: `<getAUJobSummaryResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getAUJobSummaryResponse")]
#[non_exhaustive]
pub struct GetAuJobSummaryResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    #[anet(wrapper, item = "auResponse")]
    #[builder(default)]
    pub au_summary: Vec<AuResponse>,
}

/// Get AUJobDetails Request
/// This method is used to get summary of jobs done by Account Updater.
///
/// XSD: `<getAUJobDetailsRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getAUJobDetailsRequest", request)]
#[non_exhaustive]
pub struct GetAuJobDetailsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub month: String,
    pub modified_type_filter: Option<AuJobType>,
    pub paging: Option<Paging>,
}

/// Get AUJobDetails Response
///
/// XSD: `<getAUJobDetailsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getAUJobDetailsResponse")]
#[non_exhaustive]
pub struct GetAuJobDetailsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub total_num_in_result_set: Option<i32>,
    pub au_details: Option<ListOfAuDetails>,
}

/// Get MerchantDetails Request
/// This method is used to get merchant capabilities.
///
/// XSD: `<getMerchantDetailsRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getMerchantDetailsRequest", request)]
#[non_exhaustive]
pub struct GetMerchantDetailsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
}

/// Get MerchantDetails Response
///
/// XSD: `<getMerchantDetailsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getMerchantDetailsResponse")]
#[non_exhaustive]
pub struct GetMerchantDetailsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub is_test_mode: Option<bool>,
    #[anet(wrapper, item = "processor", keep_empty)]
    #[builder(default)]
    pub processors: Vec<Processor>,
    pub merchant_name: String,
    pub gateway_id: String,
    #[anet(wrapper, item = "marketType", keep_empty)]
    #[builder(default)]
    pub market_types: Vec<String>,
    #[anet(wrapper, item = "productCode", keep_empty)]
    #[builder(default)]
    pub product_codes: Vec<String>,
    #[anet(wrapper, item = "paymentMethod", keep_empty)]
    #[builder(default)]
    pub payment_methods: Vec<PaymentMethodsType>,
    #[anet(wrapper, item = "currency", keep_empty)]
    #[builder(default)]
    pub currencies: Vec<String>,
    pub public_client_key: Option<String>,
    pub business_information: Option<CustomerAddress>,
    pub merchant_time_zone: Option<String>,
    #[anet(wrapper, item = "contactDetail")]
    #[builder(default)]
    pub contact_details: Vec<ContactDetail>,
}

/// Update MerchantDetails Request
/// This method is used for a partner to update merchant details.
///
/// XSD: `<updateMerchantDetailsRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateMerchantDetailsRequest", request)]
#[non_exhaustive]
pub struct UpdateMerchantDetailsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub is_test_mode: bool,
}

/// Update MerchantDetails Response
/// This method is used for a partner to update merchant details.
///
/// XSD: `<updateMerchantDetailsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "updateMerchantDetailsResponse")]
#[non_exhaustive]
pub struct UpdateMerchantDetailsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// This method is used to get Nonce (payment token) for an existing customer payment profile for a customer profile.
///
/// XSD: `<getCustomerPaymentProfileNonceRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerPaymentProfileNonceRequest", request)]
#[non_exhaustive]
pub struct GetCustomerPaymentProfileNonceRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub connected_access_token: String,
    pub customer_profile_id: String,
    pub customer_payment_profile_id: String,
}

/// XSD: `<getCustomerPaymentProfileNonceResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getCustomerPaymentProfileNonceResponse")]
#[non_exhaustive]
pub struct GetCustomerPaymentProfileNonceResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub opaque_data: Option<OpaqueData>,
}

/// This method is used to retrieve the Acceptance Device serial number
/// (DeviceSN) for a merchant and mobile device.
/// Authentication is via sessionToken with mobileDeviceId in merchantAuthentication.
///
/// XSD: `<getADDetailsRequest>`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getADDetailsRequest", request)]
#[non_exhaustive]
pub struct GetAdDetailsRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
}

/// This is the response to getADDetailsRequest.
/// Returns the Acceptance Device serial number (DeviceSN) in acceptanceDevicesAccount.
///
/// XSD: `<getADDetailsResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "getADDetailsResponse")]
#[non_exhaustive]
pub struct GetAdDetailsResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
    pub acceptance_devices_account: Option<AcceptanceDevicesAccount>,
}

/// This method is used to save the Acceptance Device serial number
/// (DeviceSN) for a merchant and mobile device.
/// Authentication is via sessionToken with mobileDeviceId in merchantAuthentication.
///
/// XSD: `<saveDeviceSNRequest>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "saveDeviceSNRequest", request)]
#[non_exhaustive]
pub struct SaveDeviceSnRequest {
    pub client_id: Option<String>,
    pub ref_id: Option<String>,
    pub acceptance_devices_account: AcceptanceDevicesAccount,
}

/// This is the response to saveDeviceSNRequest.
///
/// XSD: `<saveDeviceSNResponse>`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[anet(root = "saveDeviceSNResponse")]
#[non_exhaustive]
pub struct SaveDeviceSnResponse {
    pub ref_id: Option<String>,
    pub messages: Messages,
    #[anet(sensitive)]
    pub session_token: Option<String>,
}

/// Invokes `$callback!` with the path of every request type.
#[doc(hidden)]
#[macro_export]
macro_rules! __for_each_request {
    ($callback:ident) => {
        $callback! {
            $crate::schema::DecryptPaymentDataRequest,
            $crate::schema::SecurePaymentContainerRequest,
            $crate::schema::IsAliveRequest,
            $crate::schema::AuthenticateTestRequest,
            $crate::schema::ArbCreateSubscriptionRequest,
            $crate::schema::ArbUpdateSubscriptionRequest,
            $crate::schema::ArbCancelSubscriptionRequest,
            $crate::schema::ArbGetSubscriptionStatusRequest,
            $crate::schema::CreateCustomerProfileRequest,
            $crate::schema::CreateCustomerPaymentProfileRequest,
            $crate::schema::CreateCustomerShippingAddressRequest,
            $crate::schema::CreateCustomerProfileFromTransactionRequest,
            $crate::schema::GetCustomerProfileRequest,
            $crate::schema::GetCustomerPaymentProfileRequest,
            $crate::schema::GetCustomerShippingAddressRequest,
            $crate::schema::UpdateCustomerProfileRequest,
            $crate::schema::UpdateCustomerPaymentProfileRequest,
            $crate::schema::UpdateCustomerShippingAddressRequest,
            $crate::schema::DeleteCustomerProfileRequest,
            $crate::schema::DeleteCustomerPaymentProfileRequest,
            $crate::schema::DeleteCustomerShippingAddressRequest,
            $crate::schema::CreateCustomerProfileTransactionRequest,
            $crate::schema::ValidateCustomerPaymentProfileRequest,
            $crate::schema::GetCustomerProfileIdsRequest,
            $crate::schema::UpdateSplitTenderGroupRequest,
            $crate::schema::GetTransactionDetailsRequest,
            $crate::schema::GetTransactionSummaryRequest,
            $crate::schema::CreateTransactionRequest,
            $crate::schema::UpdateHeldTransactionRequest,
            $crate::schema::GetBatchStatisticsRequest,
            $crate::schema::GetSettledBatchListRequest,
            $crate::schema::GetTransactionListRequest,
            $crate::schema::GetHostedProfilePageRequest,
            $crate::schema::GetUnsettledTransactionListRequest,
            $crate::schema::GetHostedPaymentPageRequest,
            $crate::schema::MobileDeviceRegistrationRequest,
            $crate::schema::MobileDeviceLoginPinRequest,
            $crate::schema::MobileDeviceLoginVerifyPinRequest,
            $crate::schema::MobileDeviceLoginVerifyChallengeRequest,
            $crate::schema::MobileDeviceMfaLoginRequest,
            $crate::schema::LogoutRequest,
            $crate::schema::SendCustomerTransactionReceiptRequest,
            $crate::schema::ArbGetSubscriptionListRequest,
            $crate::schema::GetCustomerPaymentProfileListRequest,
            $crate::schema::ArbGetSubscriptionRequest,
            $crate::schema::GetTransactionListForCustomerRequest,
            $crate::schema::GetAuJobSummaryRequest,
            $crate::schema::GetAuJobDetailsRequest,
            $crate::schema::GetMerchantDetailsRequest,
            $crate::schema::UpdateMerchantDetailsRequest,
            $crate::schema::GetCustomerPaymentProfileNonceRequest,
            $crate::schema::GetAdDetailsRequest,
            $crate::schema::SaveDeviceSnRequest,
        }
    };
}

/// Invokes `$callback!` with the path of every response type.
#[doc(hidden)]
#[macro_export]
macro_rules! __for_each_response {
    ($callback:ident) => {
        $callback! {
            $crate::schema::DecryptPaymentDataResponse,
            $crate::schema::SecurePaymentContainerResponse,
            $crate::schema::ErrorResponse,
            $crate::schema::IsAliveResponse,
            $crate::schema::AuthenticateTestResponse,
            $crate::schema::ArbCreateSubscriptionResponse,
            $crate::schema::ArbUpdateSubscriptionResponse,
            $crate::schema::ArbCancelSubscriptionResponse,
            $crate::schema::ArbGetSubscriptionStatusResponse,
            $crate::schema::CreateCustomerProfileResponse,
            $crate::schema::CreateCustomerPaymentProfileResponse,
            $crate::schema::CreateCustomerShippingAddressResponse,
            $crate::schema::GetCustomerProfileResponse,
            $crate::schema::GetCustomerPaymentProfileResponse,
            $crate::schema::GetCustomerShippingAddressResponse,
            $crate::schema::UpdateCustomerProfileResponse,
            $crate::schema::UpdateCustomerPaymentProfileResponse,
            $crate::schema::UpdateCustomerShippingAddressResponse,
            $crate::schema::DeleteCustomerProfileResponse,
            $crate::schema::DeleteCustomerPaymentProfileResponse,
            $crate::schema::DeleteCustomerShippingAddressResponse,
            $crate::schema::CreateCustomerProfileTransactionResponse,
            $crate::schema::ValidateCustomerPaymentProfileResponse,
            $crate::schema::GetCustomerProfileIdsResponse,
            $crate::schema::UpdateSplitTenderGroupResponse,
            $crate::schema::GetTransactionDetailsResponse,
            $crate::schema::GetTransactionSummaryResponse,
            $crate::schema::CreateTransactionResponse,
            $crate::schema::UpdateHeldTransactionResponse,
            $crate::schema::GetBatchStatisticsResponse,
            $crate::schema::GetSettledBatchListResponse,
            $crate::schema::GetTransactionListResponse,
            $crate::schema::GetHostedProfilePageResponse,
            $crate::schema::GetHostedPaymentPageResponse,
            $crate::schema::GetUnsettledTransactionListResponse,
            $crate::schema::MobileDeviceRegistrationResponse,
            $crate::schema::MobileDeviceLoginPinResponse,
            $crate::schema::MobileDeviceLoginVerifyPinResponse,
            $crate::schema::MobileDeviceLoginVerifyChallengeResponse,
            $crate::schema::MobileDeviceMfaLoginResponse,
            $crate::schema::LogoutResponse,
            $crate::schema::SendCustomerTransactionReceiptResponse,
            $crate::schema::ArbGetSubscriptionListResponse,
            $crate::schema::GetCustomerPaymentProfileListResponse,
            $crate::schema::ArbGetSubscriptionResponse,
            $crate::schema::GetAuJobSummaryResponse,
            $crate::schema::GetAuJobDetailsResponse,
            $crate::schema::GetMerchantDetailsResponse,
            $crate::schema::UpdateMerchantDetailsResponse,
            $crate::schema::GetCustomerPaymentProfileNonceResponse,
            $crate::schema::GetAdDetailsResponse,
            $crate::schema::SaveDeviceSnResponse,
        }
    };
}
