// @generated by `cargo xtask codegen` from schema/AnetApiSchema.xsd and
// schema/overrides.toml. Do not edit by hand.

use bon::Builder;
use crate::Decimal;
use crate::types::{RawXml, XmlDate, XmlDateTime};
use crate::xml::AnetXml;
#[allow(unused_imports)]
use super::*;

/// XSD: `creditCardTrackType`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum CreditCardTrack {
    #[anet(sensitive)]
    Track1(String),
    #[anet(sensitive)]
    Track2(String),
}

/// XSD: `paymentSimpleType`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum PaymentSimple {
    CreditCard(CreditCardSimple),
    BankAccount(BankAccount),
}

/// XSD: `Payment choice`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum PaymentInstrument {
    CreditCard(CreditCard),
    BankAccount(BankAccount),
    TrackData(CreditCardTrack),
    EncryptedTrackData(EncryptedTrackData),
    PayPal(PayPal),
    OpaqueData(OpaqueData),
    Emv(PaymentEmv),
}

/// XSD: `paymentMaskedType`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum PaymentMasked {
    CreditCard(CreditCardMasked),
    BankAccount(BankAccountMasked),
    TokenInformation(TokenMasked),
}

/// XSD: `MerchantAuthentication choice`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum MerchantCredential {
    #[anet(sensitive, max_length = 16)]
    TransactionKey(String),
    #[anet(sensitive)]
    SessionToken(String),
    #[anet(sensitive, max_length = 40)]
    Password(String),
    ImpersonationAuthentication(ImpersonationAuthentication),
    FingerPrint(FingerPrint),
    ClientKey(String),
    #[anet(sensitive)]
    AccessToken(String),
    #[anet(sensitive)]
    ActivationCode(String),
}

/// XSD: `profileTransactionType`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum ProfileTransaction {
    ProfileTransAuthCapture(ProfileTransAuthCapture),
    ProfileTransAuthOnly(ProfileTransAuthOnly),
    ProfileTransPriorAuthCapture(ProfileTransPriorAuthCapture),
    ProfileTransCaptureOnly(ProfileTransCaptureOnly),
    ProfileTransRefund(ProfileTransRefund),
    ProfileTransVoid(ProfileTransVoid),
}

/// XSD: `ListOfAuDetails choice`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum AuDetail {
    AuUpdate(AuUpdate),
    AuDelete(AuDelete),
}

/// XSD: `GetTransactionDetailsRequest choice`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum TransactionReference {
    #[anet(pattern = "[0-9]+")]
    TransId(String),
    #[anet(max_length = 50)]
    TransrefId(String),
}

/// XSD: `CreateTransactionRequest choice`
#[derive(Clone, PartialEq, AnetXml)]
#[non_exhaustive]
pub enum CreateTransactionPayload {
    TransactionRequest(TransactionRequest),
    TransactionRequestEnc(String),
}

/// XSD: `ArrayOfSetting`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct ArrayOfSetting {
    #[builder(default)]
    pub setting: Vec<Setting>,
}

/// XSD: `driversLicenseType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct DriversLicense {
    #[anet(min_length = 5, max_length = 20)]
    pub number: String,
    #[anet(min_length = 2, max_length = 2)]
    pub state: String,
    #[anet(min_length = 8, max_length = 10)]
    pub date_of_birth: String,
}

/// XSD: `driversLicenseMaskedType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct DriversLicenseMasked {
    #[anet(length = 8)]
    pub number: String,
    #[anet(min_length = 2, max_length = 2)]
    pub state: String,
    #[anet(min_length = 8, max_length = 10)]
    pub date_of_birth: String,
}

/// XSD: `nameAndAddressType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct NameAndAddress {
    #[anet(max_length = 50)]
    pub first_name: Option<String>,
    #[anet(max_length = 50)]
    pub last_name: Option<String>,
    #[anet(max_length = 50)]
    pub company: Option<String>,
    #[anet(max_length = 60)]
    pub address: Option<String>,
    #[anet(max_length = 40)]
    pub city: Option<String>,
    #[anet(max_length = 40)]
    pub state: Option<String>,
    #[anet(max_length = 20)]
    pub zip: Option<String>,
    #[anet(max_length = 60)]
    pub country: Option<String>,
}

/// XSD: `merchantContactType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct MerchantContact {
    pub merchant_name: Option<String>,
    pub merchant_address: Option<String>,
    pub merchant_city: Option<String>,
    pub merchant_state: Option<String>,
    pub merchant_zip: Option<String>,
    #[anet(max_length = 20)]
    pub merchant_phone: Option<String>,
}

/// XSD: `acceptanceDevicesAccountType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AcceptanceDevicesAccount {
    #[anet(rename = "acceptanceDevicesID")]
    pub acceptance_devices_id: Option<String>,
    pub acceptance_devices_key: Option<String>,
    #[anet(rename = "acceptanceDevicesSN")]
    pub acceptance_devices_sn: Option<String>,
}

/// XSD: `transRetailInfoType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransRetailInfo {
    pub market_type: Option<String>,
    pub device_type: Option<String>,
    pub customer_signature: Option<String>,
    pub terminal_number: Option<String>,
}

/// XSD: `creditCardSimpleType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CreditCardSimple {
    #[anet(sensitive, min_length = 4, max_length = 16)]
    pub card_number: String,
    #[anet(min_length = 4, max_length = 7)]
    pub expiration_date: String,
}

/// XSD: `creditCardType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CreditCard {
    #[anet(flatten)]
    pub credit_card_simple: CreditCardSimple,
    #[anet(sensitive, min_length = 3, max_length = 4, pattern = "[0-9]+")]
    pub card_code: Option<String>,
    pub is_payment_token: Option<bool>,
    pub cryptogram: Option<String>,
    pub token_requestor_name: Option<String>,
    pub token_requestor_id: Option<String>,
    pub token_requestor_eci: Option<String>,
}

/// XSD: `creditCardMaskedType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CreditCardMasked {
    #[anet(sensitive, length = 8)]
    pub card_number: String,
    #[anet(min_length = 4, max_length = 7)]
    pub expiration_date: String,
    pub card_type: Option<String>,
    pub card_art: Option<CardArt>,
    #[anet(length = 6)]
    pub issuer_number: Option<String>,
    pub is_payment_token: Option<bool>,
}

/// XSD: `ccAuthenticationType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CcAuthentication {
    pub authentication_indicator: String,
    pub cardholder_authentication_value: String,
}

/// XSD: `bankAccountType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct BankAccount {
    pub account_type: Option<BankAccountType>,
    #[anet(sensitive, max_length = 9)]
    pub routing_number: String,
    #[anet(sensitive, max_length = 17)]
    pub account_number: String,
    #[anet(max_length = 22)]
    pub name_on_account: String,
    pub echeck_type: Option<EcheckType>,
    #[anet(max_length = 50)]
    pub bank_name: Option<String>,
    #[anet(max_length = 15)]
    pub check_number: Option<String>,
}

/// XSD: `bankAccountMaskedType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct BankAccountMasked {
    pub account_type: Option<BankAccountType>,
    #[anet(sensitive, length = 8)]
    pub routing_number: String,
    #[anet(sensitive, length = 8)]
    pub account_number: String,
    #[anet(max_length = 22)]
    pub name_on_account: String,
    pub echeck_type: Option<EcheckType>,
    #[anet(max_length = 50)]
    pub bank_name: Option<String>,
}

/// XSD: `opaqueDataType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct OpaqueData {
    pub data_descriptor: String,
    #[anet(sensitive)]
    pub data_value: String,
    pub data_key: Option<String>,
    pub expiration_time_stamp: Option<XmlDateTime>,
}

/// XSD: `paymentType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Payment {
    #[anet(choice)]
    pub instrument: PaymentInstrument,
    pub data_source: Option<String>,
}

/// XSD: `tokenMaskedType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TokenMasked {
    pub token_source: Option<String>,
    pub token_number: String,
    #[anet(min_length = 4, max_length = 7)]
    pub expiration_date: String,
    pub token_requestor_id: Option<String>,
}

/// XSD: `orderType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Order {
    #[anet(max_length = 20)]
    pub invoice_number: Option<String>,
    #[anet(max_length = 255)]
    pub description: Option<String>,
    pub discount_amount: Option<Decimal>,
    pub tax_is_after_discount: Option<bool>,
    #[anet(max_length = 3)]
    pub total_tax_type_code: Option<String>,
    #[anet(rename = "purchaserVATRegistrationNumber", max_length = 21)]
    pub purchaser_vat_registration_number: Option<String>,
    #[anet(rename = "merchantVATRegistrationNumber", max_length = 21)]
    pub merchant_vat_registration_number: Option<String>,
    #[anet(max_length = 15)]
    pub vat_invoice_reference_number: Option<String>,
    #[anet(max_length = 17)]
    pub purchaser_code: Option<String>,
    #[anet(max_length = 4)]
    pub summary_commodity_code: Option<String>,
    #[anet(rename = "purchaseOrderDateUTC")]
    pub purchase_order_date_utc: Option<XmlDate>,
    #[anet(max_length = 25)]
    pub supplier_order_reference: Option<String>,
    #[anet(max_length = 36)]
    pub authorized_contact_name: Option<String>,
    #[anet(max_length = 25)]
    pub card_acceptor_ref_number: Option<String>,
    #[anet(rename = "amexDataTAA1", max_length = 40)]
    pub amex_data_taa1: Option<String>,
    #[anet(rename = "amexDataTAA2", max_length = 40)]
    pub amex_data_taa2: Option<String>,
    #[anet(rename = "amexDataTAA3", max_length = 40)]
    pub amex_data_taa3: Option<String>,
    #[anet(rename = "amexDataTAA4", max_length = 40)]
    pub amex_data_taa4: Option<String>,
}

/// XSD: `orderExType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct OrderEx {
    #[anet(flatten)]
    #[builder(default)]
    pub order: Order,
    #[anet(max_length = 25)]
    pub purchase_order_number: Option<String>,
}

/// XSD: `customerType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Customer {
    pub r#type: Option<CustomerType>,
    #[anet(max_length = 20)]
    pub id: Option<String>,
    #[anet(max_length = 255)]
    pub email: Option<String>,
    #[anet(max_length = 25)]
    pub phone_number: Option<String>,
    #[anet(max_length = 25)]
    pub fax_number: Option<String>,
    pub drivers_license: Option<DriversLicense>,
    #[anet(min_length = 9, max_length = 9, pattern = "[0-9]+")]
    pub tax_id: Option<String>,
}

/// XSD: `customerDataType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerData {
    pub r#type: Option<CustomerType>,
    #[anet(max_length = 20)]
    pub id: Option<String>,
    #[anet(max_length = 255)]
    pub email: Option<String>,
    pub drivers_license: Option<DriversLicense>,
    #[anet(min_length = 8, max_length = 9)]
    pub tax_id: Option<String>,
}

/// XSD: `merchantAuthenticationType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct MerchantAuthentication {
    #[anet(max_length = 25)]
    pub name: Option<String>,
    #[anet(choice)]
    pub credential: Option<MerchantCredential>,
    #[anet(max_length = 60)]
    pub mobile_device_id: Option<String>,
    #[anet(sensitive)]
    pub enc_password: Option<String>,
    pub enc_mobile_device_id: Option<String>,
}

/// XSD: `fingerPrintType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct FingerPrint {
    pub hash_value: String,
    pub sequence: Option<String>,
    pub timestamp: String,
    pub currency_code: Option<String>,
    pub amount: Option<String>,
}

/// XSD: `cardArt`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CardArt {
    pub card_brand: Option<String>,
    pub card_image_height: Option<String>,
    pub card_image_url: Option<String>,
    pub card_image_width: Option<String>,
    pub card_type: Option<String>,
}

/// XSD: `paymentDetails`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct PaymentDetails {
    pub currency: Option<String>,
    pub promo_code: Option<String>,
    pub misc: Option<String>,
    pub gift_wrap: Option<String>,
    pub discount: Option<String>,
    pub tax: Option<String>,
    pub shipping_handling: Option<String>,
    pub sub_total: Option<String>,
    #[anet(rename = "orderID")]
    pub order_id: Option<String>,
    pub amount: Option<String>,
}

/// XSD: `webCheckOutDataType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct WebCheckOutData {
    pub r#type: WebCheckOutType,
    #[anet(min_length = 1, max_length = 64)]
    pub id: String,
    pub token: Option<WebCheckOutDataTypeToken>,
    pub bank_token: Option<BankAccount>,
}

/// XSD: `securePaymentContainerErrorType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct SecurePaymentContainerError {
    pub code: String,
    pub description: String,
}

/// XSD: `impersonationAuthenticationType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ImpersonationAuthentication {
    #[anet(max_length = 25)]
    pub partner_login_id: String,
    #[anet(max_length = 16)]
    pub partner_transaction_key: String,
}

/// XSD: `PaymentScheduleInterval`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct PaymentScheduleInterval {
    #[anet(min = "1", max = "32000")]
    pub length: i16,
    pub unit: ArbSubscriptionUnit,
}

/// XSD: `paymentScheduleType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct PaymentSchedule {
    pub interval: Option<PaymentScheduleInterval>,
    pub start_date: Option<XmlDate>,
    #[anet(min = "1", max = "32000")]
    pub total_occurrences: Option<i16>,
    #[anet(min = "0", max = "32000")]
    pub trial_occurrences: Option<i16>,
}

/// XSD: `ARBSubscriptionType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ArbSubscription {
    #[anet(max_length = 50)]
    pub name: Option<String>,
    pub payment_schedule: Option<PaymentSchedule>,
    #[anet(min = "0.01", fraction_digits = 4)]
    pub amount: Option<Decimal>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub trial_amount: Option<Decimal>,
    pub payment: Option<Payment>,
    pub order: Option<Order>,
    pub customer: Option<Customer>,
    pub bill_to: Option<NameAndAddress>,
    pub ship_to: Option<NameAndAddress>,
    pub profile: Option<CustomerProfileId>,
}

/// XSD: `ARBSubscriptionMaskedType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ArbSubscriptionMasked {
    #[anet(max_length = 50)]
    pub name: Option<String>,
    pub payment_schedule: Option<PaymentSchedule>,
    #[anet(min = "0.01", fraction_digits = 4)]
    pub amount: Option<Decimal>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub trial_amount: Option<Decimal>,
    pub status: Option<ArbSubscriptionStatus>,
    pub profile: Option<SubscriptionCustomerProfile>,
    pub order: Option<Order>,
    #[anet(wrapper, item = "arbTransaction")]
    #[builder(default)]
    pub arb_transactions: Vec<ArbTransaction>,
}

/// XSD: `subscriptionCustomerProfileType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct SubscriptionCustomerProfile {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_profile_ex: CustomerProfileEx,
    pub payment_profile: Option<CustomerPaymentProfileMasked>,
    pub shipping_profile: Option<CustomerAddressEx>,
}

/// XSD: `subscriptionPaymentType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct SubscriptionPayment {
    #[anet(min = "0")]
    pub id: i32,
    #[anet(min = "0")]
    pub pay_num: i32,
}

/// XSD: `fraudInformationType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct FraudInformation {
    #[anet(wrapper, item = "fraudFilter", keep_empty, min_occurs = 1, max_occurs = 1000)]
    #[builder(default)]
    pub fraud_filter_list: Vec<String>,
    pub fraud_action: String,
}

/// XSD: `mobileDeviceType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct MobileDevice {
    #[anet(max_length = 60)]
    pub mobile_device_id: String,
    #[anet(max_length = 60)]
    pub description: Option<String>,
    #[anet(max_length = 20)]
    pub phone_number: Option<String>,
    #[anet(max_length = 255)]
    pub device_platform: Option<String>,
    pub device_activation: Option<DeviceActivation>,
}

/// XSD: `subMerchantType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct SubMerchant {
    #[anet(max_length = 40)]
    pub identifier: String,
    #[anet(max_length = 50)]
    pub doing_business_as: Option<String>,
    #[anet(max_length = 40)]
    pub payment_service_provider_name: Option<String>,
    #[anet(max_length = 20)]
    pub payment_service_facilitator: Option<String>,
    #[anet(max_length = 40)]
    pub street_address: Option<String>,
    #[anet(max_length = 20)]
    pub phone: Option<String>,
    #[anet(max_length = 40)]
    pub email: Option<String>,
    #[anet(max_length = 20)]
    pub postal_code: Option<String>,
    #[anet(max_length = 30)]
    pub city: Option<String>,
    #[anet(max_length = 10)]
    pub region_code: Option<String>,
    #[anet(max_length = 10)]
    pub country_code: Option<String>,
}

/// XSD: `transactionRequestType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionRequest {
    pub transaction_type: TransactionType,
    pub amount: Option<Decimal>,
    pub currency_code: Option<String>,
    pub payment: Option<Payment>,
    pub profile: Option<CustomerProfilePayment>,
    pub solution: Option<Solution>,
    pub call_id: Option<String>,
    pub terminal_number: Option<String>,
    pub auth_code: Option<String>,
    pub ref_trans_id: Option<String>,
    pub split_tender_id: Option<String>,
    pub order: Option<Order>,
    #[anet(wrapper, item = "lineItem")]
    #[builder(default)]
    pub line_items: Vec<LineItem>,
    pub tax: Option<ExtendedAmount>,
    pub duty: Option<ExtendedAmount>,
    pub shipping: Option<ExtendedAmount>,
    pub tax_exempt: Option<bool>,
    pub po_number: Option<String>,
    pub customer: Option<CustomerData>,
    pub bill_to: Option<CustomerAddress>,
    pub ship_to: Option<NameAndAddress>,
    #[anet(rename = "customerIP")]
    pub customer_ip: Option<String>,
    pub cardholder_authentication: Option<CcAuthentication>,
    pub retail: Option<TransRetailInfo>,
    pub employee_id: Option<String>,
    /// Allowed values for settingName are: emailCustomer, merchantEmail, allowPartialAuth, headerEmailReceipt, footerEmailReceipt, recurringBilling, duplicateWindow, testRequest.
    pub transaction_settings: Option<ArrayOfSetting>,
    #[anet(wrapper, item = "userField", max_occurs = 20)]
    #[builder(default)]
    pub user_fields: Vec<UserField>,
    pub surcharge: Option<ExtendedAmount>,
    pub merchant_descriptor: Option<String>,
    pub sub_merchant: Option<SubMerchant>,
    pub tip: Option<ExtendedAmount>,
    pub processing_options: Option<ProcessingOptions>,
    pub subsequent_auth_information: Option<SubsequentAuthInformation>,
    pub other_tax: Option<OtherTax>,
    pub ship_from: Option<NameAndAddress>,
    pub authorization_indicator_type: Option<AuthorizationIndicator>,
    pub tap_to_phone: Option<bool>,
    pub debt_repayment_indicator: Option<bool>,
    #[anet(max_length = 1)]
    pub purchase_level: Option<String>,
    pub aft_information: Option<AftInfoBasic>,
    pub discount: Option<ExtendedAmount>,
}

/// XSD: `KeyManagementSchemeDukptMode`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct KeyManagementSchemeDukptMode {
    #[anet(rename = "PIN")]
    pub pin: Option<String>,
    #[anet(rename = "Data")]
    pub data: Option<String>,
}

/// XSD: `KeyManagementSchemeDukptDeviceInfo`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct KeyManagementSchemeDukptDeviceInfo {
    #[anet(rename = "Description")]
    pub description: String,
}

/// XSD: `KeyManagementSchemeDukptEncryptedData`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct KeyManagementSchemeDukptEncryptedData {
    #[anet(rename = "Value")]
    pub value: String,
}

/// XSD: `KeyManagementSchemeDukpt`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct KeyManagementSchemeDukpt {
    #[anet(rename = "Operation")]
    pub operation: Operation,
    #[anet(rename = "Mode")]
    pub mode: KeyManagementSchemeDukptMode,
    #[anet(rename = "DeviceInfo")]
    pub device_info: KeyManagementSchemeDukptDeviceInfo,
    #[anet(rename = "EncryptedData")]
    pub encrypted_data: KeyManagementSchemeDukptEncryptedData,
}

/// XSD: `KeyManagementScheme`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct KeyManagementScheme {
    #[anet(rename = "DUKPT")]
    pub dukpt: KeyManagementSchemeDukpt,
}

/// XSD: `KeyValue`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct KeyValue {
    #[anet(rename = "Encoding")]
    pub encoding: Encoding,
    #[anet(rename = "EncryptionAlgorithm")]
    pub encryption_algorithm: EncryptionAlgorithm,
    #[anet(rename = "Scheme")]
    pub scheme: KeyManagementScheme,
}

/// XSD: `KeyBlock`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct KeyBlock {
    #[anet(rename = "Value")]
    pub value: KeyValue,
}

/// XSD: `encryptedTrackDataType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct EncryptedTrackData {
    #[anet(rename = "FormOfPayment")]
    pub form_of_payment: KeyBlock,
}

/// XSD: `settingType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Setting {
    pub setting_name: Option<SettingName>,
    pub setting_value: Option<String>,
}

/// XSD: `permissionType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Permission {
    pub permission_name: Option<String>,
}

/// XSD: `userField`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct UserField {
    pub name: Option<String>,
    pub value: Option<String>,
}

/// XSD: `emvTag`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct EmvTag {
    pub name: Option<String>,
    pub value: Option<String>,
    pub formatted: Option<String>,
}

/// XSD: `customerPaymentProfileBaseType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct CustomerPaymentProfileBase {
    pub customer_type: Option<CustomerType>,
    pub bill_to: Option<CustomerAddress>,
}

/// XSD: `customerPaymentProfileType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerPaymentProfile {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_payment_profile_base: CustomerPaymentProfileBase,
    pub payment: Option<Payment>,
    pub drivers_license: Option<DriversLicense>,
    #[anet(min_length = 8, max_length = 9)]
    pub tax_id: Option<String>,
    pub default_payment_profile: Option<bool>,
    pub subsequent_auth_information: Option<SubsequentAuthInformation>,
    pub exclude_from_account_updater: Option<bool>,
}

/// XSD: `customerPaymentProfileExType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerPaymentProfileEx {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_payment_profile: CustomerPaymentProfile,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: Option<String>,
}

/// XSD: `customerPaymentProfileMaskedType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerPaymentProfileMasked {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_payment_profile_base: CustomerPaymentProfileBase,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: String,
    pub default_payment_profile: Option<bool>,
    pub payment: Option<PaymentMasked>,
    pub drivers_license: Option<DriversLicenseMasked>,
    #[anet(length = 8)]
    pub tax_id: Option<String>,
    #[anet(wrapper, item = "subscriptionId", pattern = "[0-9]+")]
    #[builder(default)]
    pub subscription_ids: Vec<String>,
    #[anet(max_length = 255, pattern = "[0-9a-zA-Z\\s]+")]
    pub original_network_trans_id: Option<String>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub original_auth_amount: Option<Decimal>,
    pub exclude_from_account_updater: Option<bool>,
}

/// XSD: `customerProfileBaseType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerProfileBase {
    #[anet(max_length = 20)]
    pub merchant_customer_id: Option<String>,
    #[anet(max_length = 255)]
    pub description: Option<String>,
    #[anet(max_length = 255)]
    pub email: Option<String>,
}

/// XSD: `customerProfileType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct CustomerProfile {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_profile_base: CustomerProfileBase,
    #[builder(default)]
    pub payment_profiles: Vec<CustomerPaymentProfile>,
    #[builder(default)]
    pub ship_to_list: Vec<CustomerAddress>,
    pub profile_type: Option<CustomerProfileType>,
}

/// XSD: `paymentEmvType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct PaymentEmv {
    pub emv_data: RawXml,
    pub emv_descriptor: RawXml,
    pub emv_version: RawXml,
}

/// XSD: `customerProfileExType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerProfileEx {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_profile_base: CustomerProfileBase,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
}

/// XSD: `customerProfileInfoExType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct CustomerProfileInfoEx {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_profile_ex: CustomerProfileEx,
    pub profile_type: Option<CustomerProfileType>,
}

/// XSD: `customerProfileMaskedType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct CustomerProfileMasked {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_profile_ex: CustomerProfileEx,
    #[builder(default)]
    pub payment_profiles: Vec<CustomerPaymentProfileMasked>,
    #[builder(default)]
    pub ship_to_list: Vec<CustomerAddressEx>,
    pub profile_type: Option<CustomerProfileType>,
}

/// XSD: `customerAddressType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerAddress {
    #[anet(flatten)]
    #[builder(default)]
    pub name_and_address: NameAndAddress,
    #[anet(max_length = 25)]
    pub phone_number: Option<String>,
    #[anet(max_length = 25)]
    pub fax_number: Option<String>,
    pub email: Option<String>,
}

/// XSD: `customerAddressExType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerAddressEx {
    #[anet(flatten)]
    #[builder(default)]
    pub customer_address: CustomerAddress,
    #[anet(pattern = "[0-9]+")]
    pub customer_address_id: Option<String>,
}

/// XSD: `extendedAmountType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ExtendedAmount {
    #[anet(min = "0.00", fraction_digits = 4)]
    pub amount: Decimal,
    #[anet(max_length = 31)]
    pub name: Option<String>,
    #[anet(max_length = 255)]
    pub description: Option<String>,
}

/// XSD: `otherTaxType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct OtherTax {
    pub national_tax_amount: Option<Decimal>,
    pub local_tax_amount: Option<Decimal>,
    pub alternate_tax_amount: Option<Decimal>,
    #[anet(max_length = 15)]
    pub alternate_tax_id: Option<String>,
    #[anet(total_digits = 5, fraction_digits = 5)]
    pub vat_tax_rate: Option<Decimal>,
    pub vat_tax_amount: Option<Decimal>,
}

/// XSD: `lineItemType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct LineItem {
    #[anet(min_length = 1, max_length = 31)]
    pub item_id: String,
    #[anet(min_length = 1, max_length = 31)]
    pub name: String,
    #[anet(max_length = 255)]
    pub description: Option<String>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub quantity: Decimal,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub unit_price: Decimal,
    pub taxable: Option<bool>,
    #[anet(max_length = 12)]
    pub unit_of_measure: Option<String>,
    #[anet(max_length = 2)]
    pub type_of_supply: Option<String>,
    #[anet(total_digits = 5, fraction_digits = 5)]
    pub tax_rate: Option<Decimal>,
    #[anet(fraction_digits = 4)]
    pub tax_amount: Option<Decimal>,
    pub national_tax: Option<Decimal>,
    pub local_tax: Option<Decimal>,
    #[anet(total_digits = 5, fraction_digits = 5)]
    pub vat_rate: Option<Decimal>,
    #[anet(max_length = 20)]
    pub alternate_tax_id: Option<String>,
    #[anet(max_length = 4)]
    pub alternate_tax_type: Option<String>,
    #[anet(max_length = 4)]
    pub alternate_tax_type_applied: Option<String>,
    #[anet(total_digits = 5, fraction_digits = 5)]
    pub alternate_tax_rate: Option<Decimal>,
    pub alternate_tax_amount: Option<Decimal>,
    #[anet(fraction_digits = 4)]
    pub total_amount: Option<Decimal>,
    #[anet(max_length = 12)]
    pub commodity_code: Option<String>,
    #[anet(max_length = 255)]
    pub product_code: Option<String>,
    #[anet(rename = "productSKU", max_length = 255)]
    pub product_sku: Option<String>,
    #[anet(total_digits = 5, fraction_digits = 5)]
    pub discount_rate: Option<Decimal>,
    #[anet(fraction_digits = 4)]
    pub discount_amount: Option<Decimal>,
    pub tax_included_in_total: Option<bool>,
    pub tax_is_after_discount: Option<bool>,
}

/// XSD: `profileTransAmountType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct ProfileTransAmount {
    #[anet(min = "0.01", fraction_digits = 4)]
    pub amount: Decimal,
    pub tax: Option<ExtendedAmount>,
    pub shipping: Option<ExtendedAmount>,
    pub duty: Option<ExtendedAmount>,
    #[anet(max_occurs = 30)]
    #[builder(default)]
    pub line_items: Vec<LineItem>,
}

/// XSD: `profileTransOrderType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ProfileTransOrder {
    #[anet(flatten)]
    pub profile_trans_amount: ProfileTransAmount,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: String,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: String,
    #[anet(pattern = "[0-9]+")]
    pub customer_shipping_address_id: Option<String>,
    pub order: Option<OrderEx>,
    pub tax_exempt: Option<bool>,
    pub recurring_billing: Option<bool>,
    #[anet(sensitive, min_length = 3, max_length = 4, pattern = "[0-9]+")]
    pub card_code: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub split_tender_id: Option<String>,
    pub processing_options: Option<ProcessingOptions>,
    pub subsequent_auth_information: Option<SubsequentAuthInformation>,
    pub authorization_indicator_type: Option<AuthorizationIndicator>,
}

/// XSD: `profileTransAuthCaptureType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct ProfileTransAuthCapture {
    #[anet(flatten)]
    pub profile_trans_order: ProfileTransOrder,
}

/// XSD: `profileTransAuthOnlyType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct ProfileTransAuthOnly {
    #[anet(flatten)]
    pub profile_trans_order: ProfileTransOrder,
}

/// XSD: `profileTransPriorAuthCaptureType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ProfileTransPriorAuthCapture {
    #[anet(flatten)]
    pub profile_trans_amount: ProfileTransAmount,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_shipping_address_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub trans_id: String,
}

/// XSD: `profileTransCaptureOnlyType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ProfileTransCaptureOnly {
    #[anet(flatten)]
    pub profile_trans_order: ProfileTransOrder,
    #[anet(max_length = 6)]
    pub approval_code: String,
}

/// XSD: `profileTransRefundType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ProfileTransRefund {
    #[anet(flatten)]
    pub profile_trans_amount: ProfileTransAmount,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_shipping_address_id: Option<String>,
    #[anet(min_length = 8, max_length = 8)]
    pub credit_card_number_masked: Option<String>,
    #[anet(min_length = 8, max_length = 8)]
    pub bank_routing_number_masked: Option<String>,
    #[anet(min_length = 8, max_length = 8)]
    pub bank_account_number_masked: Option<String>,
    pub order: Option<OrderEx>,
    #[anet(pattern = "[0-9]+")]
    pub trans_id: Option<String>,
}

/// XSD: `profileTransVoidType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ProfileTransVoid {
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_shipping_address_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub trans_id: String,
}

/// XSD: `transactionSummaryType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionSummary {
    #[anet(pattern = "[0-9]+")]
    pub trans_id: String,
    #[anet(rename = "submitTimeUTC")]
    pub submit_time_utc: XmlDateTime,
    pub submit_time_local: XmlDateTime,
    pub transaction_status: TransactionStatus,
    pub invoice_number: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub account_type: String,
    #[anet(sensitive)]
    pub account_number: String,
    pub settle_amount: Decimal,
    pub market_type: Option<String>,
    pub product: Option<String>,
    pub mobile_device_id: Option<String>,
    pub subscription: Option<SubscriptionPayment>,
    pub has_returned_items: Option<bool>,
    pub fraud_information: Option<FraudInformation>,
    pub profile: Option<CustomerProfileId>,
}

/// Lightweight transaction summary with only 15 essential fields
///
/// XSD: `getTransactionSummary`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct GetTransactionSummary {
    #[anet(pattern = "[0-9]+")]
    pub trans_id: String,
    #[anet(rename = "submitTimeUTC")]
    pub submit_time_utc: XmlDateTime,
    pub transaction_status: String,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub settle_amount: Decimal,
    pub response_code: i32,
    pub response_reason_code: i32,
    pub response_reason_description: String,
    pub batch: Option<BatchDetails>,
}

/// XSD: `arbTransaction`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ArbTransaction {
    #[anet(pattern = "[0-9]+")]
    pub trans_id: Option<String>,
    pub response: Option<String>,
    #[anet(rename = "submitTimeUTC")]
    pub submit_time_utc: Option<XmlDateTime>,
    pub pay_num: Option<i32>,
    pub attempt_num: Option<i32>,
}

/// XSD: `TransactionDetailsTag`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionDetailsTag {
    pub tag_id: String,
    pub data: String,
}

/// XSD: `transactionDetailsType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionDetails {
    #[anet(pattern = "[0-9]+")]
    pub trans_id: String,
    #[anet(pattern = "[0-9]+")]
    pub ref_trans_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub split_tender_id: Option<String>,
    #[anet(rename = "submitTimeUTC")]
    pub submit_time_utc: XmlDateTime,
    pub submit_time_local: XmlDateTime,
    pub transaction_type: TransactionType,
    pub transaction_status: TransactionStatus,
    pub response_code: i32,
    pub response_reason_code: i32,
    pub subscription: Option<SubscriptionPayment>,
    pub response_reason_description: String,
    #[anet(max_length = 6)]
    pub auth_code: Option<String>,
    #[anet(rename = "AVSResponse", max_length = 1)]
    pub avs_response: Option<String>,
    #[anet(max_length = 1)]
    pub card_code_response: Option<String>,
    #[anet(rename = "CAVVResponse", max_length = 1)]
    pub cavv_response: Option<String>,
    #[anet(rename = "FDSFilterAction")]
    pub fds_filter_action: Option<String>,
    #[anet(wrapper, item = "FDSFilter", rename = "FDSFilters")]
    #[builder(default)]
    pub fds_filters: Vec<FdsFilter>,
    pub batch: Option<BatchDetails>,
    pub order: Option<OrderEx>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub requested_amount: Option<Decimal>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub auth_amount: Decimal,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub settle_amount: Decimal,
    pub tax: Option<ExtendedAmount>,
    pub shipping: Option<ExtendedAmount>,
    pub duty: Option<ExtendedAmount>,
    #[anet(wrapper, item = "lineItem")]
    #[builder(default)]
    pub line_items: Vec<LineItem>,
    #[anet(fraction_digits = 4)]
    pub prepaid_balance_remaining: Option<Decimal>,
    pub tax_exempt: Option<bool>,
    pub payment: PaymentMasked,
    pub customer: Option<CustomerData>,
    pub bill_to: Option<CustomerAddress>,
    pub ship_to: Option<NameAndAddress>,
    pub recurring_billing: Option<bool>,
    #[anet(rename = "customerIP")]
    pub customer_ip: Option<String>,
    pub product: Option<String>,
    pub entry_mode: Option<String>,
    pub market_type: Option<String>,
    pub mobile_device_id: Option<String>,
    pub customer_signature: Option<String>,
    #[anet(wrapper, item = "returnedItem")]
    #[builder(default)]
    pub returned_items: Vec<ReturnedItem>,
    pub solution: Option<Solution>,
    #[anet(wrapper, item = "tag", min_occurs = 1)]
    #[builder(default)]
    pub emv_details: Vec<TransactionDetailsTag>,
    pub profile: Option<CustomerProfileId>,
    pub surcharge: Option<ExtendedAmount>,
    pub employee_id: Option<String>,
    pub tip: Option<ExtendedAmount>,
    pub other_tax: Option<OtherTax>,
    pub ship_from: Option<NameAndAddress>,
    #[anet(max_length = 255, pattern = "[0-9a-zA-Z\\s]+")]
    pub network_trans_id: Option<String>,
    #[anet(max_length = 255, pattern = "[0-9a-zA-Z\\s]+")]
    pub original_network_trans_id: Option<String>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub original_auth_amount: Option<Decimal>,
    pub authorization_indicator: Option<String>,
    pub merchant_advice: Option<MerchantAdvice>,
    pub tap_to_phone: Option<bool>,
    pub debt_repayment_indicator: Option<bool>,
    #[anet(max_length = 1)]
    pub purchase_level: Option<String>,
    pub aft_information: Option<AftInfoBasic>,
    pub discount: Option<ExtendedAmount>,
}

/// XSD: `solutionType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Solution {
    pub id: String,
    pub name: Option<String>,
    pub vendor_name: Option<String>,
}

/// XSD: `returnedItemType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ReturnedItem {
    #[anet(pattern = "[0-9]+")]
    pub id: String,
    #[anet(rename = "dateUTC")]
    pub date_utc: XmlDateTime,
    pub date_local: XmlDateTime,
    pub code: String,
    pub description: String,
}

/// XSD: `FDSFilterType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct FdsFilter {
    pub name: String,
    pub action: String,
}

/// XSD: `batchDetailsType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct BatchDetails {
    #[anet(pattern = "[0-9]+")]
    pub batch_id: String,
    #[anet(rename = "settlementTimeUTC")]
    pub settlement_time_utc: Option<XmlDateTime>,
    pub settlement_time_local: Option<XmlDateTime>,
    pub settlement_state: SettlementState,
    pub payment_method: Option<String>,
    pub market_type: Option<String>,
    pub product: Option<String>,
    #[anet(wrapper, item = "statistic")]
    #[builder(default)]
    pub statistics: Vec<BatchStatistic>,
}

/// XSD: `batchStatisticType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct BatchStatistic {
    pub account_type: String,
    pub charge_amount: Decimal,
    pub charge_count: i32,
    pub refund_amount: Decimal,
    pub refund_count: i32,
    pub void_count: i32,
    pub decline_count: i32,
    pub error_count: i32,
    pub returned_item_amount: Option<Decimal>,
    pub returned_item_count: Option<i32>,
    pub chargeback_amount: Option<Decimal>,
    pub chargeback_count: Option<i32>,
    pub correction_notice_count: Option<i32>,
    pub charge_charge_back_amount: Option<Decimal>,
    pub charge_charge_back_count: Option<i32>,
    pub refund_charge_back_amount: Option<Decimal>,
    pub refund_charge_back_count: Option<i32>,
    pub charge_returned_items_amount: Option<Decimal>,
    pub charge_returned_items_count: Option<i32>,
    pub refund_returned_items_amount: Option<Decimal>,
    pub refund_returned_items_count: Option<i32>,
}

/// XSD: `TransactionResponsePrePaidCard`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponsePrePaidCard {
    pub requested_amount: Option<String>,
    pub approved_amount: Option<String>,
    pub balance_on_card: Option<String>,
}

/// XSD: `TransactionResponseMessage`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponseMessage {
    pub code: Option<String>,
    pub description: Option<String>,
}

/// XSD: `TransactionResponseError`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponseError {
    pub error_code: Option<String>,
    pub error_text: Option<String>,
}

/// XSD: `TransactionResponseSplitTenderPayment`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponseSplitTenderPayment {
    pub trans_id: Option<String>,
    pub response_code: Option<String>,
    pub response_to_customer: Option<String>,
    pub auth_code: Option<String>,
    #[anet(sensitive)]
    pub account_number: Option<String>,
    pub account_type: Option<String>,
    pub requested_amount: Option<String>,
    pub approved_amount: Option<String>,
    pub balance_on_card: Option<String>,
}

/// XSD: `TransactionResponseSecureAcceptance`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponseSecureAcceptance {
    #[anet(rename = "SecureAcceptanceUrl")]
    pub secure_acceptance_url: Option<String>,
    #[anet(rename = "PayerID")]
    pub payer_id: Option<String>,
    #[anet(rename = "PayerEmail")]
    pub payer_email: Option<String>,
}

/// XSD: `TransactionResponseEmvResponse`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponseEmvResponse {
    pub tlv_data: Option<String>,
    #[anet(wrapper, item = "tag", min_occurs = 1)]
    #[builder(default)]
    pub tags: Vec<EmvTag>,
}

/// XSD: `transactionResponse`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct TransactionResponse {
    pub response_code: Option<String>,
    pub raw_response_code: Option<String>,
    pub auth_code: Option<String>,
    pub avs_result_code: Option<String>,
    pub cvv_result_code: Option<String>,
    pub cavv_result_code: Option<String>,
    pub trans_id: Option<String>,
    #[anet(rename = "refTransID")]
    pub ref_trans_id: Option<String>,
    pub trans_hash: Option<String>,
    pub test_request: Option<String>,
    #[anet(sensitive)]
    pub account_number: Option<String>,
    pub entry_mode: Option<String>,
    pub account_type: Option<String>,
    pub split_tender_id: Option<String>,
    pub pre_paid_card: Option<TransactionResponsePrePaidCard>,
    #[anet(wrapper, item = "message")]
    #[builder(default)]
    pub messages: Vec<TransactionResponseMessage>,
    /// Not in the XSD, but sent by the API.
    pub message: Option<TransactionResponseMessage>,
    #[anet(wrapper, item = "error")]
    #[builder(default)]
    pub errors: Vec<TransactionResponseError>,
    #[anet(wrapper, item = "splitTenderPayment")]
    #[builder(default)]
    pub split_tender_payments: Vec<TransactionResponseSplitTenderPayment>,
    #[anet(wrapper, item = "userField", max_occurs = 20)]
    #[builder(default)]
    pub user_fields: Vec<UserField>,
    pub ship_to: Option<NameAndAddress>,
    pub secure_acceptance: Option<TransactionResponseSecureAcceptance>,
    pub emv_response: Option<TransactionResponseEmvResponse>,
    pub trans_hash_sha2: Option<String>,
    pub profile: Option<CustomerProfileId>,
    #[anet(max_length = 255, pattern = "[0-9a-zA-Z\\s]+")]
    pub network_trans_id: Option<String>,
    pub merchant_advice: Option<MerchantAdvice>,
}

/// XSD: `ContactDetailType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct ContactDetail {
    #[anet(max_length = 255)]
    pub email: Option<String>,
    #[anet(max_length = 50)]
    pub first_name: Option<String>,
    #[anet(max_length = 50)]
    pub last_name: Option<String>,
}

/// XSD: `pinDeliveryRequestType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct PinDeliveryRequest {
    pub delivery_method: DeliveryMethod,
    #[anet(sensitive)]
    pub activation_code: String,
}

/// XSD: `pinVerifyRequestType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct PinVerifyRequest {
    pub pin: String,
    pub biometrics_public_key: Option<String>,
    #[anet(sensitive)]
    pub activation_code: String,
}

/// Allowed values for settingName are: headerEmailReceipt and footerEmailReceipt
///
/// XSD: `emailSettingsType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct EmailSettings {
    #[anet(flatten)]
    #[builder(default)]
    pub array_of_setting: ArrayOfSetting,
    #[anet(attribute)]
    pub version: Option<i64>,
}

/// XSD: `Message`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Message {
    pub code: String,
    pub text: String,
}

/// XSD: `messagesType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct Messages {
    pub result_code: MessageType,
    #[anet(min_occurs = 1)]
    #[builder(default)]
    pub message: Vec<Message>,
}

/// XSD: `createProfileResponse`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CreateProfileResponse {
    pub messages: Messages,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
    #[anet(wrapper, item = "numericString", pattern = "[0-9]+")]
    #[builder(default)]
    pub customer_payment_profile_id_list: Vec<String>,
    #[anet(wrapper, item = "numericString", pattern = "[0-9]+")]
    #[builder(default)]
    pub customer_shipping_address_id_list: Vec<String>,
}

/// XSD: `heldTransactionRequestType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct HeldTransactionRequest {
    pub action: AfdsTransaction,
    pub ref_trans_id: String,
}

/// XSD: `TransactionListSorting`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct TransactionListSorting {
    pub order_by: TransactionListOrderField,
    pub order_descending: bool,
}

/// XSD: `payPalType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct PayPal {
    #[anet(max_length = 2048)]
    pub success_url: Option<String>,
    #[anet(max_length = 2048)]
    pub cancel_url: Option<String>,
    #[anet(max_length = 2)]
    pub paypal_lc: Option<String>,
    #[anet(max_length = 127)]
    pub paypal_hdr_img: Option<String>,
    #[anet(max_length = 6)]
    pub paypal_payflowcolor: Option<String>,
    #[anet(rename = "payerID", max_length = 255)]
    pub payer_id: Option<String>,
}

/// XSD: `Paging`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct Paging {
    #[anet(min = "1", max = "1000")]
    pub limit: i32,
    #[anet(min = "1", max = "100000")]
    pub offset: i32,
}

/// XSD: `ARBGetSubscriptionListSorting`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct ArbGetSubscriptionListSorting {
    pub order_by: ArbGetSubscriptionListOrderField,
    pub order_descending: bool,
}

/// XSD: `SubscriptionDetail`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct SubscriptionDetail {
    pub id: i32,
    pub name: Option<String>,
    pub status: ArbSubscriptionStatus,
    #[anet(rename = "createTimeStampUTC")]
    pub create_time_stamp_utc: XmlDateTime,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub total_occurrences: i32,
    pub past_occurrences: i32,
    pub payment_method: PaymentMethod,
    #[anet(sensitive)]
    pub account_number: Option<String>,
    pub invoice: Option<String>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub amount: Decimal,
    pub currency_code: Option<String>,
    pub customer_profile_id: i32,
    pub customer_payment_profile_id: i32,
    pub customer_shipping_profile_id: Option<i32>,
}

/// XSD: `customerProfileSummaryType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerProfileSummary {
    pub customer_profile_id: Option<String>,
    pub description: Option<String>,
    pub merchant_customer_id: String,
    pub email: Option<String>,
    pub created_date: XmlDateTime,
}

/// XSD: `customerProfilePaymentType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerProfilePayment {
    pub create_profile: Option<bool>,
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: Option<String>,
    pub payment_profile: Option<PaymentProfile>,
    #[anet(pattern = "[0-9]+")]
    pub shipping_profile_id: Option<String>,
}

/// XSD: `paymentProfile`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct PaymentProfile {
    #[anet(pattern = "[0-9]+")]
    pub payment_profile_id: String,
    #[anet(sensitive, min_length = 3, max_length = 4, pattern = "[0-9]+")]
    pub card_code: Option<String>,
}

/// XSD: `CustomerPaymentProfileSorting`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct CustomerPaymentProfileSorting {
    pub order_by: CustomerPaymentProfileOrderField,
    pub order_descending: bool,
}

/// XSD: `customerPaymentProfileListItemType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerPaymentProfileListItem {
    pub default_payment_profile: Option<bool>,
    pub customer_payment_profile_id: i32,
    pub customer_profile_id: i32,
    pub bill_to: CustomerAddress,
    pub payment: PaymentMasked,
    #[anet(max_length = 255, pattern = "[0-9a-zA-Z\\s]+")]
    pub original_network_trans_id: Option<String>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub original_auth_amount: Option<Decimal>,
    pub exclude_from_account_updater: Option<bool>,
}

/// XSD: `customerProfileIdType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct CustomerProfileId {
    #[anet(pattern = "[0-9]+")]
    pub customer_profile_id: String,
    #[anet(pattern = "[0-9]+")]
    pub customer_payment_profile_id: Option<String>,
    #[anet(pattern = "[0-9]+")]
    pub customer_address_id: Option<String>,
}

/// XSD: `auResponseType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AuResponse {
    pub au_reason_code: String,
    pub profile_count: i64,
    pub reason_description: String,
}

/// XSD: `ListOfAUDetailsType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct ListOfAuDetails {
    #[anet(choice)]
    #[builder(default)]
    pub details: Vec<AuDetail>,
}

/// XSD: `auUpdateType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct AuUpdate {
    #[anet(flatten)]
    pub au_details: AuDetails,
    pub new_credit_card: CreditCardMasked,
    pub old_credit_card: CreditCardMasked,
}

/// XSD: `auDeleteType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[non_exhaustive]
pub struct AuDelete {
    #[anet(flatten)]
    pub au_details: AuDetails,
    pub credit_card: CreditCardMasked,
}

/// XSD: `auDetailsType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AuDetails {
    #[anet(rename = "customerProfileID")]
    pub customer_profile_id: i64,
    #[anet(rename = "customerPaymentProfileID")]
    pub customer_payment_profile_id: i64,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[anet(rename = "updateTimeUTC")]
    pub update_time_utc: String,
    pub au_reason_code: String,
    pub reason_description: String,
}

/// XSD: `processingOptions`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct ProcessingOptions {
    pub is_first_recurring_payment: Option<bool>,
    pub is_first_subsequent_auth: Option<bool>,
    pub is_subsequent_auth: Option<bool>,
    pub is_stored_credentials: Option<bool>,
}

/// XSD: `authorizationIndicatorType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[non_exhaustive]
pub struct AuthorizationIndicator {
    pub authorization_indicator: Option<AuthIndicator>,
}

/// XSD: `subsequentAuthInformation`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct SubsequentAuthInformation {
    #[anet(max_length = 255, pattern = "[0-9a-zA-Z\\s]+")]
    pub original_network_trans_id: Option<String>,
    #[anet(min = "0.00", fraction_digits = 4)]
    pub original_auth_amount: Option<Decimal>,
    pub reason: Option<MerchantInitTransReason>,
}

/// XSD: `merchantAdviceType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct MerchantAdvice {
    #[anet(pattern = "[0-9a-zA-Z\\s]+")]
    pub code: String,
    pub description: Option<String>,
}

/// XSD: `processorType`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct Processor {
    #[anet(max_length = 255)]
    pub name: String,
    pub id: i32,
    #[anet(wrapper, item = "cardType", max_occurs = 30)]
    #[builder(default)]
    pub card_types: Vec<String>,
}

/// XSD: `webCheckOutDataTypeToken`
#[derive(Clone, PartialEq, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct WebCheckOutDataTypeToken {
    #[anet(sensitive, min_length = 4, max_length = 16)]
    pub card_number: String,
    #[anet(min_length = 4, max_length = 7)]
    pub expiration_date: String,
    #[anet(sensitive, min_length = 3, max_length = 4, pattern = "[0-9]+")]
    pub card_code: Option<String>,
    #[anet(min_length = 1, max_length = 20)]
    pub zip: Option<String>,
    #[anet(min_length = 1, max_length = 64)]
    pub full_name: Option<String>,
}

/// XSD: `aftInfoBasicType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AftInfoBasic {
    pub aft_indicator: Option<bool>,
    #[anet(max_length = 2)]
    pub business_application_id: Option<String>,
    pub recipient_information: Option<AftRecipientInformation>,
    pub sender_information: Option<AftSenderInformation>,
}

/// XSD: `aftRecipientInformationType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AftRecipientInformation {
    #[anet(max_length = 35)]
    pub first_name: Option<String>,
    #[anet(max_length = 35)]
    pub middle_name: Option<String>,
    #[anet(max_length = 35)]
    pub last_name: Option<String>,
    #[anet(max_length = 50)]
    pub address: Option<String>,
    #[anet(max_length = 25)]
    pub city: Option<String>,
    #[anet(max_length = 2)]
    pub state: Option<String>,
    #[anet(max_length = 10)]
    pub zip: Option<String>,
    #[anet(max_length = 2)]
    pub country: Option<String>,
    #[anet(max_length = 10)]
    pub account_id: Option<String>,
    #[anet(max_length = 2)]
    pub account_type: Option<String>,
}

/// XSD: `aftSenderInformationType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AftSenderInformation {
    #[anet(max_length = 35)]
    pub first_name: Option<String>,
    #[anet(max_length = 35)]
    pub middle_name: Option<String>,
    #[anet(max_length = 35)]
    pub last_name: Option<String>,
    #[anet(max_length = 50)]
    pub name: Option<String>,
    #[anet(max_length = 50)]
    pub address: Option<String>,
    #[anet(max_length = 25)]
    pub city: Option<String>,
    #[anet(max_length = 2)]
    pub state: Option<String>,
    #[anet(max_length = 10)]
    pub zip: Option<String>,
    #[anet(max_length = 2)]
    pub country: Option<String>,
    #[anet(max_length = 25)]
    pub phone_number: Option<String>,
    #[anet(max_length = 1)]
    pub r#type: Option<String>,
    pub account: Option<AftSenderAccountInformation>,
    #[anet(min_length = 8, max_length = 10)]
    pub date_of_birth: Option<String>,
    #[anet(max_length = 2)]
    pub identification_number: Option<String>,
    #[anet(max_length = 4)]
    pub personal_id_type: Option<String>,
    #[anet(max_length = 19)]
    pub reference_number: Option<String>,
}

/// XSD: `aftSenderAccountInformationType`
#[derive(Clone, PartialEq, Default, AnetXml, Builder)]
#[builder(on(String, into))]
#[non_exhaustive]
pub struct AftSenderAccountInformation {
    #[anet(max_length = 2)]
    pub funds_source: Option<String>,
    #[anet(max_length = 20)]
    pub number: Option<String>,
    #[anet(max_length = 2)]
    pub r#type: Option<String>,
}
