//! Compares the vendored XSD with the Python client's `schema.py`, which was generated
//! from an older XSD, and renders the differences as Markdown.
//!
//! Types are matched by XML name, case-insensitively (xsdata changes the casing of
//! class names). Only top-level types are compared; anonymous nested types are
//! covered through their parents' element lists.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::xsd::{ComplexType, ElementType, Particle, Schema};

/// A named type's own elements (and attributes), or an enumeration's values.
#[derive(Default)]
struct TypeShape {
    /// The name as written in its source.
    name: String,
    is_enum: bool,
    members: BTreeSet<String>,
}

type Shapes = BTreeMap<String, TypeShape>;

pub fn report(schema: &Schema, schema_py: &str) -> String {
    let (xsd_types, xsd_messages) = xsd_shapes(schema);
    let (py_types, py_messages) = python_shapes(schema_py);

    let mut out = String::new();
    out.push_str("# Schema drift: live XSD vs. python-authorizenet\n\n");
    out.push_str(
        "Generated by `cargo xtask drift`. Compares `schema/AnetApiSchema.xsd` with the \
         Python client's `schema.py`, which was generated from an older version of the XSD.\n\n",
    );
    section(&mut out, "API messages", &xsd_messages, &py_messages);
    section(&mut out, "Types", &xsd_types, &py_types);
    out
}

fn section(out: &mut String, title: &str, xsd: &Shapes, py: &Shapes) {
    let _ = writeln!(out, "## {title}\n");
    let only = |a: &Shapes, b: &Shapes| -> Vec<String> {
        a.iter()
            .filter(|(key, _)| !b.contains_key(*key))
            .map(|(_, shape)| format!("`{}`", shape.name))
            .collect()
    };
    list(out, "Only in the live XSD", &only(xsd, py));
    list(
        out,
        "Only in schema.py (removed from the XSD)",
        &only(py, xsd),
    );

    let mut changed = String::new();
    for (key, x) in xsd {
        let Some(p) = py.get(key) else { continue };
        let added: Vec<_> = x
            .members
            .difference(&p.members)
            .map(|m| format!("`{m}`"))
            .collect();
        let removed: Vec<_> = p
            .members
            .difference(&x.members)
            .map(|m| format!("`{m}`"))
            .collect();
        if added.is_empty() && removed.is_empty() {
            continue;
        }
        let what = if x.is_enum { "values" } else { "elements" };
        let _ = write!(changed, "- `{}`:", x.name);
        if !added.is_empty() {
            let _ = write!(changed, " added {what} {}", added.join(", "));
        }
        if !removed.is_empty() {
            let sep = if added.is_empty() { "" } else { ";" };
            let _ = write!(changed, "{sep} removed {what} {}", removed.join(", "));
        }
        changed.push('\n');
    }
    out.push_str("### Changed\n\n");
    if changed.is_empty() {
        out.push_str("None.\n\n");
    } else {
        out.push_str(&changed);
        out.push('\n');
    }
}

fn list(out: &mut String, title: &str, items: &[String]) {
    let _ = writeln!(out, "### {title}\n");
    if items.is_empty() {
        out.push_str("None.\n\n");
    } else {
        for item in items {
            let _ = writeln!(out, "- {item}");
        }
        out.push('\n');
    }
}

fn own_members(ct: &ComplexType) -> BTreeSet<String> {
    let mut members = BTreeSet::new();
    for particle in &ct.content {
        match particle {
            Particle::Element(e) => {
                members.insert(e.name.clone());
            }
            Particle::Choice(c) => members.extend(c.members.iter().map(|m| m.name.clone())),
        }
    }
    members.extend(ct.attributes.iter().map(|a| format!("@{}", a.name)));
    members
}

fn xsd_shapes(schema: &Schema) -> (Shapes, Shapes) {
    let mut types = Shapes::new();
    for st in &schema.simple_types {
        if st.enumeration.is_empty() {
            continue;
        }
        let name = st.name.clone().expect("named");
        types.insert(
            name.to_lowercase(),
            TypeShape {
                name,
                is_enum: true,
                members: st.enumeration.iter().cloned().collect(),
            },
        );
    }
    for ct in &schema.complex_types {
        let name = ct.name.clone().expect("named");
        types.insert(
            name.to_lowercase(),
            TypeShape {
                members: own_members(ct),
                name,
                is_enum: false,
            },
        );
    }
    let mut messages = Shapes::new();
    for el in &schema.elements {
        let members = match &el.ty {
            ElementType::Complex(ct) => own_members(ct),
            _ => BTreeSet::new(),
        };
        messages.insert(
            el.name.to_lowercase(),
            TypeShape {
                name: el.name.clone(),
                is_enum: false,
                members,
            },
        );
    }
    (types, messages)
}

/// Reads top-level classes from xsdata-generated `schema.py`: their XML names (from
/// `class Meta: name = ...`, else the class name), their fields' XML names, and enum
/// values. Classes whose `Meta` sets a namespace are root elements.
fn python_shapes(source: &str) -> (Shapes, Shapes) {
    let mut types = Shapes::new();
    let mut messages = Shapes::new();
    let mut lines = source.lines().peekable();
    while let Some(line) = lines.next() {
        let Some(header) = line.strip_prefix("class ") else {
            continue;
        };
        let class_name = header
            .split(['(', ':'])
            .next()
            .unwrap_or_default()
            .to_owned();
        let is_enum = header.contains("(Enum)");
        let mut xml_name = class_name.clone();
        let mut is_root = false;
        let mut members = BTreeSet::new();
        let mut field: Option<(String, Option<String>, bool)> = None;
        let mut in_meta = false;
        // Inside a nested class (an anonymous XSD type), whose fields are not ours.
        let mut in_nested = false;

        let finish_field = |field: &mut Option<(String, Option<String>, bool)>,
                            members: &mut BTreeSet<String>| {
            if let Some((py_name, xml, attribute)) = field.take() {
                let name = xml.unwrap_or(py_name);
                members.insert(if attribute { format!("@{name}") } else { name });
            }
        };

        while let Some(next) = lines.peek() {
            if next.starts_with("class ") {
                break;
            }
            let next = lines.next().expect("peeked");
            if next.starts_with("    class Meta:") {
                in_meta = true;
                continue;
            }
            if next.starts_with("    class ") {
                finish_field(&mut field, &mut members);
                in_nested = true;
                continue;
            }
            if in_nested {
                let class_level = next.starts_with("    ") && !next.starts_with("     ");
                if !class_level {
                    continue;
                }
                in_nested = false;
            }
            if in_meta {
                if let Some(rest) = next.strip_prefix("        name = ") {
                    xml_name = rest.trim_matches('"').to_owned();
                    continue;
                }
                if next.starts_with("        namespace = ") {
                    is_root = true;
                    continue;
                }
                if !next.starts_with("        ") {
                    in_meta = false;
                }
            }
            if is_enum {
                if let Some((_, value)) = next
                    .strip_prefix("    ")
                    .and_then(|l| l.split_once(" = \""))
                {
                    members.insert(value.trim_end_matches('"').to_owned());
                }
                continue;
            }
            // A field declaration at class level: `    name: type = field(`.
            if let Some(decl) = next.strip_prefix("    ")
                && !decl.starts_with(' ')
                && decl.contains(": ")
                && decl.contains("field(")
            {
                finish_field(&mut field, &mut members);
                let py_name = decl.split(':').next().unwrap_or_default().to_owned();
                field = Some((py_name, None, false));
                continue;
            }
            if let Some((_, xml, attribute)) = field.as_mut() {
                let trimmed = next.trim();
                if let Some(rest) = trimmed.strip_prefix("\"name\": ") {
                    *xml = Some(rest.trim_end_matches(',').trim_matches('"').to_owned());
                } else if trimmed == "\"type\": \"Attribute\"," {
                    *attribute = true;
                }
            }
        }
        finish_field(&mut field, &mut members);
        if class_name == "Enum" {
            continue;
        }
        let shape = TypeShape {
            name: xml_name.clone(),
            is_enum,
            members,
        };
        let target = if is_root { &mut messages } else { &mut types };
        target.insert(xml_name.to_lowercase(), shape);
    }
    (types, messages)
}
