//! Renders the model as Rust source.

use std::collections::{BTreeSet, HashSet};

use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;

use crate::model::{Card, ChoiceDef, EnumDef, Field, FieldKind, Model, RustType, StructDef};

pub const HEADER: &str = "// @generated by `cargo xtask codegen` from schema/AnetApiSchema.xsd and\n\
                          // schema/overrides.toml. Do not edit by hand.\n\n";

/// The generated files, as (file name, contents).
pub fn render(model: &Model) -> Vec<(&'static str, String)> {
    let defaults: HashSet<&str> = model
        .structs
        .iter()
        .filter(|s| s.default)
        .map(|s| s.name.as_str())
        .collect();

    let enums: Vec<TokenStream> = model.enums.iter().map(enum_def).collect();
    let choices = model.choices.iter().map(choice_def);
    let (roots, types): (Vec<&StructDef>, Vec<&StructDef>) =
        model.structs.iter().partition(|s| s.root.is_some());

    let type_items: Vec<TokenStream> = choices
        .chain(types.iter().map(|s| struct_def(s, &defaults)))
        .collect();
    let type_uses = uses(
        model
            .choices
            .iter()
            .flat_map(|c| c.variants.iter().map(|v| &v.ty))
            .chain(types.iter().flat_map(|s| s.fields.iter().map(|f| &f.ty))),
    );
    let root_items: Vec<TokenStream> = roots.iter().map(|s| struct_def(s, &defaults)).collect();
    let root_uses = uses(roots.iter().flat_map(|s| s.fields.iter().map(|f| &f.ty)));

    let mut messages = file(quote! { #root_uses #(#root_items)* });
    messages.push_str(&root_macros(&roots));

    vec![
        (
            "enums.rs",
            file(quote! {
                use crate::xml::AnetEnum;
                #(#enums)*
            }),
        ),
        ("types.rs", file(quote! { #type_uses #(#type_items)* })),
        ("messages.rs", messages),
    ]
}

fn file(tokens: TokenStream) -> String {
    let parsed: syn::File = syn::parse2(tokens).expect("generated code parses");
    let code = prettyplease::unparse(&parsed);
    // Separate top-level items with a blank line.
    let code = code
        .replace("\n}\n", "\n}\n\n")
        .replace(";\n///", ";\n\n///");
    format!("{HEADER}{}", code.trim_end_matches('\n').to_owned() + "\n")
}

/// `use` items for the built-in and derive names a file needs.
fn uses<'a>(types: impl Iterator<Item = &'a RustType>) -> TokenStream {
    let mut value_types = BTreeSet::new();
    let mut decimal = false;
    for ty in types {
        match ty {
            RustType::Decimal => decimal = true,
            RustType::Date => {
                value_types.insert("XmlDate");
            }
            RustType::DateTime => {
                value_types.insert("XmlDateTime");
            }
            RustType::Raw => {
                value_types.insert("RawXml");
            }
            _ => {}
        }
    }
    let value_types: Vec<Ident> = value_types.into_iter().map(ident).collect();
    let decimal = decimal.then(|| {
        quote!(
            use crate::Decimal;
        )
    });
    let value_types =
        (!value_types.is_empty()).then(|| quote!(use crate::types::{#(#value_types),*};));
    quote! {
        use bon::Builder;
        #decimal
        #value_types
        use crate::xml::AnetXml;
        #[allow(unused_imports)]
        use super::*;
    }
}

fn ident(name: &str) -> Ident {
    Ident::new(name, Span::call_site())
}

/// A field identifier, raw if it is a keyword (`type` -> `r#type`).
fn field_ident(name: &str) -> Ident {
    if syn::parse_str::<Ident>(name).is_ok() {
        ident(name)
    } else {
        Ident::new_raw(name, Span::call_site())
    }
}

/// `#[doc]` attributes, escaping text that rustdoc would read as markup.
fn docs(doc: Option<&str>, origin: Option<&str>) -> TokenStream {
    let mut lines: Vec<String> = Vec::new();
    if let Some(doc) = doc {
        lines.extend(doc.lines().map(escape_doc));
    }
    if let Some(origin) = origin {
        if !lines.is_empty() {
            lines.push(String::new());
        }
        lines.push(format!("XSD: `{origin}`"));
    }
    let lines = lines.iter().map(|l| format!(" {l}"));
    quote!(#(#[doc = #lines])*)
}

fn escape_doc(line: &str) -> String {
    let mut out = String::with_capacity(line.len());
    for word in line.split_inclusive(' ') {
        let bare = word.trim_end();
        if bare.starts_with("http://") || bare.starts_with("https://") {
            out.push('<');
            out.push_str(bare);
            out.push('>');
            out.push_str(&word[bare.len()..]);
            continue;
        }
        for c in word.chars() {
            if matches!(c, '<' | '>' | '[' | ']' | '*' | '_' | '`' | '#') {
                out.push('\\');
            }
            out.push(c);
        }
    }
    out
}

fn rust_type(ty: &RustType) -> TokenStream {
    match ty {
        RustType::String => quote!(String),
        RustType::Bool => quote!(bool),
        RustType::I16 => quote!(i16),
        RustType::I32 => quote!(i32),
        RustType::I64 => quote!(i64),
        RustType::Decimal => quote!(Decimal),
        RustType::Date => quote!(XmlDate),
        RustType::DateTime => quote!(XmlDateTime),
        RustType::Raw => quote!(RawXml),
        RustType::Named(name) => {
            let name = ident(name);
            quote!(#name)
        }
    }
}

fn enum_def(def: &EnumDef) -> TokenStream {
    let name = ident(&def.name);
    let doc = docs(def.doc.as_deref(), Some(&def.origin));
    let variants = def.variants.iter().map(|v| {
        let var = ident(&v.name);
        let value = &v.value;
        quote! {
            #[anet(value = #value)]
            #var,
        }
    });
    quote! {
        #doc
        #[derive(Debug, Clone, PartialEq, Eq, Hash, AnetEnum)]
        #[non_exhaustive]
        pub enum #name {
            #(#variants)*
            /// A value the schema does not list.
            #[anet(other)]
            Other(String),
        }
    }
}

fn choice_def(def: &ChoiceDef) -> TokenStream {
    let name = ident(&def.name);
    let doc = docs(def.doc.as_deref(), Some(&def.origin));
    let variants = def.variants.iter().map(|v| {
        let var = ident(&v.name);
        let ty = rust_type(&v.ty);
        let rename = (v.xml != lower_first(&v.name)).then(|| {
            let xml = &v.xml;
            quote!(rename = #xml)
        });
        let sensitive = v.sensitive.then(|| quote!(sensitive));
        let args: Vec<TokenStream> = rename.into_iter().chain(sensitive).collect();
        let attr = (!args.is_empty()).then(|| quote!(#[anet(#(#args),*)]));
        quote! {
            #attr
            #var(#ty),
        }
    });
    quote! {
        #doc
        #[derive(Clone, PartialEq, AnetXml)]
        #[non_exhaustive]
        pub enum #name {
            #(#variants)*
        }
    }
}

fn struct_def(def: &StructDef, defaults: &HashSet<&str>) -> TokenStream {
    let name = ident(&def.name);
    let origin = match &def.root {
        Some(root) => format!("<{root}>"),
        None => def.origin.clone(),
    };
    let doc = docs(def.doc.as_deref(), Some(&origin));
    let default = def.default.then(|| quote!(Default,));
    let into = def
        .fields
        .iter()
        .any(|f| f.ty == RustType::String && f.card != Card::List)
        .then(|| quote!(#[builder(on(String, into))]));
    let root = def.root.as_ref().map(|root| {
        if def.request {
            quote!(#[anet(root = #root, request)])
        } else {
            quote!(#[anet(root = #root)])
        }
    });
    let fields = def.fields.iter().map(|f| field_def(f, defaults));
    quote! {
        #doc
        #[derive(Clone, PartialEq, #default AnetXml, Builder)]
        #into
        #root
        #[non_exhaustive]
        pub struct #name {
            #(#fields)*
        }
    }
}

fn field_def(f: &Field, defaults: &HashSet<&str>) -> TokenStream {
    let name = field_ident(&f.name);
    let doc = docs(f.doc.as_deref(), None);
    let inner = rust_type(&f.ty);
    let ty = match f.card {
        Card::Required => inner,
        Card::Optional => quote!(Option<#inner>),
        Card::List => quote!(Vec<#inner>),
    };

    let mut args = Vec::new();
    let renamed = f.xml != default_xml_name(&f.name);
    match &f.kind {
        FieldKind::Element => {}
        FieldKind::Wrapped { item, keep_empty } => {
            args.push(quote!(wrapper, item = #item));
            if *keep_empty {
                args.push(quote!(keep_empty));
            }
        }
        FieldKind::Attribute => args.push(quote!(attribute)),
        FieldKind::Flatten => args.push(quote!(flatten)),
        FieldKind::Choice => args.push(quote!(choice)),
    }
    if renamed && !matches!(f.kind, FieldKind::Flatten | FieldKind::Choice) {
        let xml = &f.xml;
        args.push(quote!(rename = #xml));
    }
    if f.sensitive {
        args.push(quote!(sensitive));
    }
    let anet = (!args.is_empty()).then(|| quote!(#[anet(#(#args),*)]));

    let builder_default = match (&f.kind, f.card) {
        (_, Card::List) => true,
        (FieldKind::Flatten, _) => {
            matches!(&f.ty, RustType::Named(n) if defaults.contains(n.as_str()))
        }
        _ => false,
    };
    let builder = builder_default.then(|| quote!(#[builder(default)]));

    quote! {
        #doc
        #anet
        #builder
        pub #name: #ty,
    }
}

/// The derive's default element name for a field: `ref_trans_id` -> `refTransId`.
fn default_xml_name(field: &str) -> String {
    let mut out = String::new();
    for (i, part) in field.split('_').filter(|p| !p.is_empty()).enumerate() {
        if i == 0 {
            out.push_str(part);
        } else {
            let mut chars = part.chars();
            if let Some(first) = chars.next() {
                out.extend(first.to_uppercase());
                out.push_str(chars.as_str());
            }
        }
    }
    out
}

/// The derive's default element name for a choice variant: `CreditCard` -> `creditCard`.
fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// `macro_rules!` listing every request and response type, so that code handling all
/// messages (tests, `AnyResponse`) stays in sync with the schema.
fn root_macros(roots: &[&StructDef]) -> String {
    let list = |suffix: &str| {
        roots
            .iter()
            .filter(|s| s.root.as_deref().is_some_and(|r| r.ends_with(suffix)))
            .map(|s| format!("            $crate::schema::{},\n", s.name))
            .collect::<String>()
    };
    let mut out = String::new();
    for (name, suffix, what) in [
        ("__for_each_request", "Request", "request"),
        ("__for_each_response", "Response", "response"),
    ] {
        out.push_str(&format!(
            "\n/// Invokes `$callback!` with the path of every {what} type.\n\
             #[doc(hidden)]\n\
             #[macro_export]\n\
             macro_rules! {name} {{\n    \
                 ($callback:ident) => {{\n        \
                     $callback! {{\n{}        }}\n    \
                 }};\n\
             }}\n",
            list(suffix)
        ));
    }
    out
}
